### ISSUE TITLE
APK size: "unused dependencies"?

### ISSUE THREAD

**Issue by IzzySoft** [1fexd/LinkSheet#1]
I just found your app today. Though none of my devices are on Android-12 yet, the corresponding OTAs are announced for this year already – which is when your app might come in to help me staying organized. So thanks for making it available!

I was just wondering about the size of the APK. Not being an Android dev myself, I might not have the "deep insight" and my questions may sound "stupid" – but if I don't ask them, I'll "stay that stupid forever" :see_no_evil: I was checking "what is inside" with my library scanner, and am wondering about some libs which are explicitly "for older versions of Android", whether they are indeed needed here or "slipped in" accidentally as (unused?) dependencies of some other libraries:

* [Android Support v4](https://developer.android.com/reference/android/support/v4/app/package-summary.html) ("**compatibility** and component libraries"; if it's the former it might be obsolete)
* [Interpolator](https://developer.android.com/jetpack/androidx/releases/interpolator) (AndroidX library to use animation interpolators **on older platforms**)
* [Print](https://developer.android.com/jetpack/androidx/releases/print) (a library to **print photos, docs, and other graphics and images**)
* [OkHttp](https://github.com/square/okhttp) (an **HTTP+HTTP/2 client** for Android and Java applications – your app does not even have network permissions)
* [OkHttp okio Framework](https://github.com/square/okio) (name suggests it's also mostly about HTTP requests)

Maybe I'm completely off-track here, in which case I apologize – but could you please take a look and give me "a hint" (or "clean up" should I have been correct with my analysis – maybe something like [Minify android app but do not obfuscate it](https://stackoverflow.com/q/35853593/2533433) could take care for that more-or-less automatically)? Thanks in advance!

**Comment by 1fexd** [comment]
Hey, damn, first issue by Izzy himself, what an honor. I have removed unused dependencies and enabled minify in the latest release.

**Comment by IzzySoft** [comment]
:rofl: Well… looks like I hit the mark here – and you did a very good job implementing the suggestion: from 13 down to a little more than 3 MB is quite a thing, thanks! So let me increase versions kept from 2 to 3, as they fit in easily now [here](https://apt.izzysoft.de/fdroid/index/apk/fe.linksheet) :partying_face: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you wish :smiley:
