### ISSUE TITLE
[potential bug] App sorting works with suggested app, rest stay alphabetical.

### ISSUE THREAD

**Issue by Gravemind2015** [1fexd/LinkSheet#10]
Easier to explain with screenshots. In this instance, let's take a reddit link, a reddit app (infinity) and a specific browser (Firefox focus). Say we don't use any other options.

In screenshot # 1, if Firefox focus was previously selected, it appears on top. Suggested apps also come on top for the rest of list. This is expected.

Then we select infinity this time, go back and tap on link again. Now as per screenshot # 2, infinity is on top as expected. But Firefox focus isn't 2nd as the 2nd most used app, but the rest of the options are just sorted alphabetically. Focus is actually the last, hidden and the user needs to scroll to get it, even though the rest of the apps have never been used to open reddit links.

So, in conclusion it should switch infinity and focus in the top and 2nd position depending on usage, but only dedicated apps remain in 1st or 2nd line, rest are sorted alphabetically. 

I hope I explained this properly. Dunno if this is intended behaviour😅. Again thanks for the app, it really saves a lot of time on android 12. 
![Screenshot_20230226-222313_LinkSheet_1_1](https://user-images.githubusercontent.com/116586720/221425271-f3531607-6e48-419a-addd-ab59d19f0c91.png)
![Screenshot_20230226-222327_LinkSheet_1_1_1](https://user-images.githubusercontent.com/116586720/221425576-7b21f933-0db6-4dc9-8ade-10513d1902b4.png)
![Screenshot_20230226-224022_LinkSheet_1_1](https://user-images.githubusercontent.com/116586720/221425589-c50f614e-94f4-4c33-bcd3-559a6fe27b7b.png)

**Comment by 1fexd** [comment]
Will look into this for the next release.

**Comment by 1fexd** [comment]
I have created a debug release [here](https://github.com/1fexd/LinkSheet/releases/tag/0.0.12-debug) could you please test if it meet your requirements?

**Comment by Gravemind2015** [comment]
> I have created a debug release [here](https://github.com/1fexd/LinkSheet/releases/tag/0.0.12-debug) could you please test if it meet your requirements?

Did a clean install, setup as usual and yeah, it's working great. I've attached a screenshot, testing with random apps again and again. It's just like what the commit added above references, sorts by history/usage stats and then name. Thanks, this is really helpful for me (and probably others too who see redundant browsers and/or apps, especially for list view).
![Screenshot_20230301-042116_LinkSheet_1](https://user-images.githubusercontent.com/116586720/222000693-7cb13158-43ab-4be2-a956-adb5c14ab1b1.png)
![Screenshot_20230301-042520_LinkSheet_1](https://user-images.githubusercontent.com/116586720/222000705-1ac1aead-ff26-4094-8dde-af6ac1a70108.png)

**Comment by 1fexd** [comment]
Thanks for testing.
