### ISSUE TITLE
feature(1.0.0): Finish "Request private browsing" button

### ISSUE THREAD

**Issue by 1fexd** [1fexd/LinkSheet#101]
The button currently does not show up in grid mode. Additionally, we should evaluate wheter we could also display an icon to unclutter the bottom sheet. We should also check if this feature can be implemented for Chromium-based browsers or if it only works in Firefox.

**Comment by RuthlessRuler** [comment]
Bromite has an option for this to open links in Incognito.

**Comment by 1fexd** [comment]
Hi, could you tell me where? I don't use Bromite. Thanks!

**Comment by RuthlessRuler** [comment]
![Screenshot_20230627-202504_Bromite](https://github.com/1fexd/LinkSheet/assets/20885012/764ccbc3-6f50-4132-829f-02e31897c2c5)
It has this option.

**Comment by kunalagra** [comment]
Maybe we can have the app icon with a Private/Incognito mask/icon beside it on for Grid layout?

**Comment by 1fexd** [comment]
Sound like an interesting idea. However, I have little motivation to implement this now, it is gonna take a while, sorry :(
