### ISSUE TITLE
Preferred Browser feature does not allow selecting any browser from the list

### ISSUE THREAD

**Issue by AnonRS3** [1fexd/LinkSheet#12]
See the following screen recording for more details. 

https://user-images.githubusercontent.com/54009117/221439298-1bdd26e2-d468-4224-913c-330ee3c3398f.mp4

As a result, any links that should he handled by the browser are required to be manually set individually per domain.

**Comment by Gravemind2015** [comment]
Can confirm. In fact I can't select any of my installed browsers (checked bromite, fennec, Firefox, Firefox beta, or firefox focus). Can only toggle between 'always ask' and 'none'.

**Comment by 1fexd** [comment]
Thanks for reporting, will fix in the next release.
