### ISSUE TITLE
Crashes caused by newer system services being unavailable

### ISSUE THREAD

**Issue by LightWayUp** [1fexd/LinkSheet#120]
### Bug description

The app crashes when:
- On Android 10 and 11, in LinkSheet navigate to Settings > Apps > Preferred apps
- On Android 9 and below, simply open LinkSheet

In functions, checks like `if (AndroidVersion.AT_LEAST_API_31_S)` are performed. However, fields are only annotated with [`@RequiresApi`](https://developer.android.com/reference/kotlin/androidx/annotation/RequiresApi), which is a hint and does not prevent initialization.  
Therefore, [`domainVerificationManager` field in `PreferredAppSettingsViewModel`](https://github.com/1fexd/LinkSheet/blob/3393a6ab1dac7ec3df6f3b622869eea864ad9dc2/app/src/main/java/fe/linksheet/composable/settings/apps/preferred/PreferredAppSettingsViewModel.kt#L27-L28) causes crash as Android can't find the class of the service:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/pm/verify/domain/DomainVerificationManager;
(Obfuscated stack trace omitted)
Caused by: java.lang.ClassNotFoundException: android.content.pm.verify.domain.DomainVerificationManager
    ... 62 more
```
Similarly for [`roleManager` field in `MainViewModel`](https://github.com/1fexd/LinkSheet/blob/ed44db5c73e01214512ded058a9d303ef71ba2bc/app/src/main/java/fe/linksheet/module/viewmodel/MainViewModel.kt#L24-L25):
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/role/RoleManager;
(Obfuscated stack trace omitted)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.role.RoleManager" on path: DexPathList[[zip file "/data/app/fe.linksheet.nightly-66axovlUfdaoJtmvjdnJCA==/base.apk"],nativeLibraryDirectories=[/data/app/fe.linksheet.nightly-66axovlUfdaoJtmvjdnJCA==/lib/x86_64, /system/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 62 more
```
There are more fields annotated this way in `AppsWhichCanOpenLinksViewModel`, but users can't reach that route below Android 12, so there's no impact there.

### Version

Nightly

### Previous version

0.0.31

### Device

Android Emulator

### Android version

Android 11

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks for the very detailed bug report, I thought the Android Gradle plugin does some magic at compile time to transform code using this annotation, but apparently it does not.
