### ISSUE TITLE
feature(1.0.0): Ability to Custom Sort Link Operations

### ISSUE THREAD

**Issue by RuthlessRuler** [1fexd/LinkSheet#128]
### Feature description

So often lot of links (like shortened) have tracking URLs only after they have been redirected. 

For eg, links from Social Media like Twitter are generally shortened and may often contain tracking params after they have been redirected.

It would be great if we can define our own custom Sort Order or maybe have ClearURL as last by default as this helps to solve major of these cases as you need to clean the destination URL.

**Comment by 1fexd** [comment]
True. Will check if it makes more sense to apply ClearURLs before the redirection (or before **and** after)

**Comment by 1fexd** [comment]
Will be implemented in 1.0.0.

**Comment by 1fexd** [comment]
ClearURLs/FastForward now run before **and after** following redirects.
