### ISSUE TITLE
Close dialog on press on copy link

### ISSUE THREAD

**Issue by xmha97** [1fexd/LinkSheet#13]
Hi, thanks for making this app.
Please add the option below:
- Close dialog on press on "Copy Link" button.
![Screenshot_2023-02-27-02-12-04-273_fe.linksheet.jpg](https://user-images.githubusercontent.com/23485114/221442013-7c2866b2-57fe-492d-bd51-b434fc848610.jpg)

**Comment by 1fexd** [comment]
Will implement in next release.

**Comment by xmha97** [comment]
> Will implement in next release.

Thanks 🙏
