### ISSUE TITLE
Show app info

### ISSUE THREAD

**Issue by xmha97** [1fexd/LinkSheet#14]
Please add the feature below:
- Show app info on long press on items

https://user-images.githubusercontent.com/23485114/221702854-cf73d945-a98f-4c92-b9d2-3bf0b05d24f4.mp4

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
This feature is not working.

https://user-images.githubusercontent.com/23485114/222568456-f7983faa-aa1c-4643-ac8e-494f91f751ad.mp4

**Comment by D3SOX** [comment]
Seems to conflict with the `Enable single tap` option

**Comment by xmha97** [comment]
> Seems to conflict with the `Enable single tap` option. I get the same result when I enable it but it works when it's disabled.

I think it's possible to fix this issue.

**Comment by 1fexd** [comment]
You can now double tap an app to open the app info when single tap is enabled; Long pressing will select the app (it was like this before)

**Comment by xmha97** [comment]
Thanks 🙏
It's good.
