### ISSUE TITLE
Handle URLs from Chrome 

### ISSUE THREAD

**Issue by zt64** [1fexd/LinkSheet#144]
### Feature description

Normally when tapping a Google play url in chrome it will open in the respective app. But turning off Google play link handling results in it just opening in a new tab. I would expect link sheet to appear instead, prompting for what app to use. 

I'm unsure if this is a Samsung specific issue or if this isn't possible to implement.

**Comment by 1fexd** [comment]
I'm on my phone right now, but from just pure speculation, Chrome probably first tries to find a native app to handle a clicked link (LinkSheet doesn't count here as it poses as a browser). If there is none, the link will just be opened in another tab (or the same one).

Is there no "Open in app" button hidden away in the menu next to the tabselector? Personally, I am a Firefox user which has such a button and allows me to summon LinkSheet.

I am afraid that there's nothing I can do here (without root at least, or without patching Chrome in some way)

**Comment by zt64** [comment]
That's a little unfortunate to hear. And there is no open in app feature either which is disappointing.

**Comment by 1fexd** [comment]
But there is a fix (although a bit annoying): There is this share button right? Just tap that one, then select LinkSheet, then the link will open in LinkSheet :)

Getting kind of invested in this now, I think I have another workaround though.

**Comment by 1fexd** [comment]
For future reference: [This behavior is defined in Chromium here](https://source.chromium.org/chromium/chromium/src/+/main:components/external_intents/android/java/src/org/chromium/components/external_intents/ExternalNavigationHandler.java?q=queryIntentActivities)

**Comment by 1fexd** [comment]
Okay, so of course, it's not as easy as I initially thought (is it ever?), but I have an idea how to solve this:

What if LinkSheet allows the user to install "stub" compat apps which have exactly the same URL handling capabilities as the original app (e.g. Youtube). The user can create such a compat app on the fly by patching a stub apk stored/downloaded by LinkSheet (with the help of ReVanced's patcher). These compat apps are hidden from the user's launcher, and upon receiving a link, they just forward it to LinkSheet.

Not sure if I am playing 5D chess here, or if this is unnecessarily overkill. Either way, I'm going to try implementing this later. ;)

**Comment by zt64** [comment]
I like that idea. That makes me wonder is it possible to make a stub that handles all URLs? Not sure if Android would allow just a "*" for the url string

**Comment by 1fexd** [comment]
Nope, that's not possible. If it were, we wouldn't need such a complicated setup as LinkSheet already does this.

**Comment by 1fexd** [comment]
I just tried this and holy shit. It actually works.

**Comment by 1fexd** [comment]
Have you encountered this on other websites as well?

**Comment by 1fexd** [comment]
To get a MVP out to you asap, I have created a new repository [here](https://github.com/1fexd/LinkSheetCompat/releases/tag/0.0.1). The app does not have a launcher, and you will have to go into settings to make it the default Youtube URL handler. After that, clicking Youtube links in the Google search on Chrome, LinkSheet will open (does not work with debug/nightly for now).

**Comment by zt64** [comment]
Just tried it and can confirm it works. Could the compat app handle more than just YouTube? if theres no limit maybe it could handle a large list of URLs

**Comment by 1fexd** [comment]
> Just tried it and can confirm it works. Could the compat app handle more than just YouTube? if theres no limit maybe it could handle a large list of URLs

It can, yes. So in theory, this issue is resolved now, but in practice, people will have to wait for new domains to be added, which may take a few days.

**Comment by 1fexd** [comment]
Closing this as we now have the Compat app. The settings menu also mentions that such an app exists and where it can be downloaded.

**Comment by zt64** [comment]
Thanks!

**Comment by JasonHK** [comment]
> Is there no "Open in app" button hidden away in the menu next to the tabselector? Personally, I am a Firefox user which has such a button and allows me to summon LinkSheet.

@1fexd I think Firefox changed something, the "open in app" option in Firefox no longer show up unless the "open supported links" for the app is enabled in Android Settings.

**Comment by 1fexd** [comment]
Works fine for me - please open a new ticket with app versions, logs, etc.

**Comment by JasonHK** [comment]
Looks like it's because I was using  a outdated version, latest nightly is fine
