### ISSUE TITLE
Share button is not working!

### ISSUE THREAD

**Issue by xmha97** [1fexd/LinkSheet#15]
Hi, the share button is not working!

https://user-images.githubusercontent.com/23485114/221732768-64e0176d-4c56-4a2c-b4b2-ea1e88073958.mp4

**Comment by D3SOX** [comment]
Works fine for me on LineageOS 20, might be a MIUI or whatever this is specific problem.

**Comment by 1fexd** [comment]
This looks like it's an issue with MIUI, works fine for me on stock Android 13

**Comment by xmha97** [comment]
There are many bugs in MIUI ROMs and this cannot be denied but I am facing this problem only in your app and share button is working properly in all apps.
In any case, I'm sure that the problem can be solved, so please don't close the issue so that others can see and comment on it.
Thanks 🙏

**Comment by dgudim** [comment]
Works for me on OneUI 5.0

**Comment by 1fexd** [comment]
Can you provide a logcat @xmha97?

**Comment by Tanmandal** [comment]
Same here on miui

**Comment by 1fexd** [comment]
Could you provide a logcat @Tanmandal?
