### ISSUE TITLE
Skip button for special (internal) links

### ISSUE THREAD

**Issue by Validbit** [1fexd/LinkSheet#158]
### Feature description

In some applications there is infinite/long loading for links (compatible/whitelisted apps) that are meant to be internal/system (e.g. social sign in, settings link (battery optimizations)) (e.g. in Peloton, miui status bar)

Could there be a skip button during the loading or other reliable option to make these links work with the app?

**Comment by 1fexd** [comment]
Hello, where exactly are you experiencing this issue? You mentioned Peleton, so I tested the app, but was not able to reproduce any issues - everythin worked fine.

**Comment by Validbit** [comment]
Yesterday (before I let update many apps) even pictures in official GitHub app wouldn't load on click, but now it works.

The social sign-in still doesn't work for me in some apps (incl. Peloton)

I'll gradually list here more actions (and in which apps) - where it'll happen, and enclose related logs from app:


I'll let you know when enough was gathered, let me know what more info do you want.

**Comment by 1fexd** [comment]
I checked out the Facebook login in Peleton and it works fine with all link manipulation settings turned off - LinkSheet still pops up, but it asks me to open Chrome where the page appears to load fine. 

I have noticed a few problems with some link manipulation settings where it won't stop loading, I'll investigate further.

**Comment by 1fexd** [comment]
Could you please test this on the [latest nightly build](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip)?

**Comment by Validbit** [comment]
The nightly didn't help (I'll be giving examples and logs here (gradually):

Youtube links (from descriptions)

**Comment by 1fexd** [comment]
> Youtube links (from descriptions)

Can't reproduce, clicking Youtube description links works fine for me.

**Comment by Validbit** [comment]
The nightly didn't help (I'll be giving examples and logs here (gradually):

Youtube links (from descriptions)
Github
Play store (from descriptions)

**Comment by Validbit** [comment]
I've sent you logs gathered so far (through mail so I can send device fingerprint - details)

**Comment by 1fexd** [comment]
Which email address did you use?I did not get any emails

**Comment by Validbit** [comment]
validbit outlook.com sent to specified adress on gitlab: @ 420blaze.it

**Comment by 1fexd** [comment]
Either this is a MIUI specific issue, or maybe your internet connection blocks some hosts (via DNS)? Would you mind trying again on latest nightly, and sending an unredacted log? Everything works fine on my Pixel.

**Comment by Validbit** [comment]
I'm sending new logs from new version, howewer it didn't help.

I'm not censoring the logs, I let the "loading link..." run for more than 10s now each (and all optional log checkboxes were checked.

The app worked before on this phone, now even direct share doesn't work - it's likely due to my setup of the app.
**LibRedirect** is what's directly causing this

**Comment by 1fexd** [comment]
Still can't reproduce, could you please do a screenrecording (first show your settings, then what's not working)

**Comment by 1fexd** [comment]
Hello, is there still anything to do here? Can you check it out on the latest nightly build and if you still encounter any issues, please open a new one, thank you very much.
