### ISSUE TITLE
Interface for querying selected domains

### ISSUE THREAD

**Issue by zacharee** [1fexd/LinkSheet#161]
### Feature description

For [Mastodon Redirect](https://github.com/zacharee/MastodonRedirect), I have a setup notice that shows up if links aren't selected using Android's internal system, and disappears once they are, but I don't have a way to check if someone's selected the domains in LinkSheet.

I think it should be possible to create a Service that external apps can start which returns a well-defined Binder interface to query which links are selected, or whether all links are selected.

For the former (which links), it'd probably need to use the hidden ParceledListSlice API, since a list of over 10k domains will likely go over the transaction size limit. For the latter, it could return a simple boolean.

The AIDL could look something like:

```aidl
import android.content.pm.ParceledListSlice;

interface ILinkSheetService {
    ParceledListSlice<String> getSelectedDomains(String packageName) = 1;
    boolean areAllDomainsSelected(String packageName) = 2;
}
```

and the implementation could do a check to make sure that the passed package name matches the calling package name:

```kotlin
fun validateIdentity(passedPackage: String) {
    val callingPackages = packageManager.getPackagesForUid(Binder.getCallingUid())
    if (!callingPackages.contains(passedPackage)) {
        throw IllegalAccessException("Calling package is not $passedPackage!")
    }
}
```

The Service shouldn't need to be always running, just exported. An external app can then start it, bind to it, and request it be shut down as needed (although it should probably have some sort of binding counter so it doesn't shut down if something else is still bound).

A stretch goal could be a library to encapsulate the AIDL and connection logic, but it should be simple enough to just copy in some code manually, as long as the AIDL IDs remain constant.

**Comment by 1fexd** [comment]
Thanks for the detailed write-up! 

> but I don't have a way to check if someone's selected the domains in LinkSheet.

What exactly do you mean by that? Selected as in within LinkSheet in the preferred app section (where the user tells LinkSheet to always use a selected app for a certain domain?), or do you mean the system's link handling? Because LinkSheet doesn't use that, and even if it did, you could query the state like this:

```kotlin
val domainVerificationManager = getSystemService<DomainVerificationManager>()!!
val state = domainVerificationManager.getDomainVerificationUserState("fe.linksheet")
```

**Comment by zacharee** [comment]
I mean LinkSheet's internal user selection.

Zachary Wander

**Comment by 1fexd** [comment]
Sorry but I don't quite understand, what are we trying to achieve here?

**Comment by zacharee** [comment]
I'd like a way to hide the "Set Up Link Hanling" banner I have in my app when a user has selected all of the supported links from inside LinkSheet.

Something like the domain verification API in Android, but for exposing LinkSheet's state instead of Android's.

**Comment by 1fexd** [comment]
Oh yeah that sounds like a good idea, can you recommend any resources/documentation on how to work with AIDLs/implement services? I have never done this before

**Comment by zacharee** [comment]
I can make a PR later with an implementation so we can discuss concrete details.
