### ISSUE TITLE
Libredirect for twitter needs more incoming domains like x.com and maybe others like fxtwitter.com

### ISSUE THREAD

**Issue by Kezxo** [1fexd/LinkSheet#168]
### Bug description

So twitter.com has a new name and domain, `x.com` is an official link that leads to tweets now. If you click these links linksheet wont redirect you to nitter.

There are also other projects that exist to fix embeds of tweets on discord and telegram, you use them by changing the domain which fixes the embed but if you click the link the website redirects you to twitter.com. Here are the two big ones:

- `vxtwitter.com`, github: https://github.com/dylanpdx/BetterTwitFix
- `fxtwitter.com`, github: https://github.com/FixTweet/FixTweet This also use these domains:
  - `twittpr.com`
  - `fixupx.com`

Clicking tweet links with these domains won't get redirected by linksheet which isn't unexpected but I would really like it if they were so I don't have to connect to twitter.com in my browser.

Maybe the solution could be that you could add any domain and have linksheet treat it like a twitter domain? Maybe that's hard to implement but adding support for these four domains would be awesome.

Somewhat related issue: #136

In any case adding support for `x.com` is a must since its the new official domain.

### Version

0.0.33

### Device

OnePlus 8T

### Android version

OxygenOS 13 (based on Android 13)

### Application log or crash log

See #167 .

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
I have created an issue upstream for `x.com`: https://github.com/libredirect/browser_extension/issues/799

The redirection topic will be handled/decided on in #136.

**Comment by Kezxo** [comment]
Any update on `x.com`? It seems that it got added upstream?
