### ISSUE TITLE
[0.0.10] URL becomes case insensitive

### ISSUE THREAD

**Issue by kzshantonu** [1fexd/LinkSheet#17]
Link tapped: `https://youtu.be/eUh1Cf5MjLY`

Link actually opened in browser: `https://m.youtube.com/watch?v=euh1cf5mjly`

**Comment by kzshantonu** [comment]
The same happens when using Share to

**Comment by 1fexd** [comment]
Damn, you are absolutely right, just meant to lowercase the host. Will fix as soon as I get home

**Comment by 1fexd** [comment]
Fixed in [0.0.11](https://github.com/1fexd/LinkSheet/releases/tag/0.0.11)
