### ISSUE TITLE
[0.0.11] all browsers shown even when a single preferred browser selected 

### ISSUE THREAD

**Issue by kzshantonu** [1fexd/LinkSheet#18]

**Comment by 1fexd** [comment]
Hi there, thanks for reporting this issue. Can you check if [0.0.13-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.13-debug) behaves as expected?

**Comment by 1fexd** [comment]
Should be fixed in [0.0.14-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.14-debug)

**Comment by kzshantonu** [comment]
Seems fine now
