### ISSUE TITLE
Offer nightly as APK

### ISSUE THREAD

**Issue by nichu42** [1fexd/LinkSheet#190]
### Feature description

Hi there,

Would it be possible for you to offer the nightlies as APK instead of ZIP?
That would enable users to download and update the app automatically via Obtainium.

Thanks for your consideration.

**Comment by 1fexd** [comment]
Sadly, as described [here](https://github.com/marketplace/actions/upload-a-build-artifact#zipped-artifact-downloads), artifacts are always zipped, I can't influence that. Also, how would Obtainium be able to detect a new version? I just checked and it can't check for workflow artifacts. What I could do, however, is publish nightlies as pre-releases, but that would create a lot of pre-releases as nightlies are built on each push.

**Comment by nichu42** [comment]
If you don't mind doing that, I'd like to make use of it. If not, I'll switch back to LS stable when the next release is out.

**Comment by 1fexd** [comment]
Still setting things up, but nightlies should be available as Github releases in the repo [LinkSheetNightly](https://github.com/1fexd/LinkSheetNightly). Appears to work fine with Obtainium.

**Comment by nichu42** [comment]
Thank you very much. Set up and running. ☺️
