### ISSUE TITLE
Add native app to list of browsers

### ISSUE THREAD

**Issue by nichu42** [1fexd/LinkSheet#191]
### Feature description

I'm uncertain if this is the right place to ask (or if I should open an issue with Mastodon Redirect):
Would it be possible to allow native apps added to the browser list in LinkSheet?

Background:
I am using Fedilab (Mastodon app) in combination with Mastodon Redirect and LinkSheet.
A special thing about Mastodon is that you can only see information that was previously downloader to your own instance (server). Sometimes you come along posts or profiles that your home instance is now aware of yet. The Fedilab app allows you to open  threads or profiles in a browser, so you can view the information that is stored on an external instance. Now with Mastodon Redirect and LinkSheet, if I tip on such a link, it reverts me back to the Fedilab app because the URL is on the Mastodon Redirect list, and I can still only see what my server news about this thread or profile.
With adding Mastodon Redirect to the list of browsers, I hope to be able to choose opening a link in Fedilab (via Mastodon Redirect) or my browser.

**Comment by 1fexd** [comment]
@zacharee

**Comment by zacharee** [comment]
This should be solved with the latest LinkSheet Nightly.
