### ISSUE TITLE
Setting the Intent referrer "properly"

### ISSUE THREAD

**Issue by zacharee** [1fexd/LinkSheet#192]
### Feature description

The workaround I used to forward the original Intent referrer through LinkSheet to the destination uses a custom Intent extra.

Ideally, I think LinkSheet should be completely transparent in its operation, meaning the `Activity#getReferrer()` method in itself in the destination app should return the original referrer instead of LinkSheet's package name.

It looks like the most robust way to do this involves setting a standard extra value along with using a hidden API method to start Activities instead of the standard `Context#.startActivity()`.

The code might look something like this:

```kotlin
val launchIntent = {the Intent LinkSheet generates to launch}

// This should be enough for most apps, since it's the first priority of return when `Activity#getReferrer()` is called.
launchIntent.putExtra(Intent.EXTRA_REFERRER, Uri.parse("android-app://${originalReferrer}"))

// This will set `Activity#mReferrer` in the target so even apps using reflection to bypass the Intent extra value won't see LinkSheet as the referrer.
ActivityTaskManager.getService().startActivity(
    ActivityThread.currentActivityThread(),
    originalReferrer, context.attributionTag,
    intent, intent.resolveTypeIfNeeded(context.contentResolver),
    null, null, 0, 0, null, null,
)
```

I'm planning to make a PR with this soon. I'm writing it here for documentation.

**Comment by 1fexd** [comment]
Can we close this then?

**Comment by zacharee** [comment]
Yep
