### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by xmha97** [1fexd/LinkSheet#2]
Hi, thanks for this app.
Please add the copy URL button.

![Screenshot_2023-02-23-22-57-17-288_fe.linksheet.jpg](https://user-images.githubusercontent.com/23485114/221010380-fbe1b723-6dfb-41a3-9ac0-365671fb0c65.jpg)

**Comment by dgudim** [comment]
Yes, a copy url button would be very useful, +1

**Comment by 1fexd** [comment]
Will be implemented in the next release.

**Comment by 1fexd** [comment]
Setting has been implemented in [0.0.7](https://github.com/1fexd/LinkSheet/releases/tag/0.0.7)

**Comment by xmha97** [comment]
Thanks 👍
