### ISSUE TITLE
infinite loading after clicking on a link

### ISSUE THREAD

**Issue by carbolymer** [1fexd/LinkSheet#211]
### Bug description

After clicking on a link: https://www.walkmyworld.com/posts/tegalalang-rice-terraces

Linksheet is stuck at "loading"
![Screenshot_20231011-202332_LinkSheet](https://github.com/1fexd/LinkSheet/assets/228866/c0c89686-e523-4c90-919d-c02120d42060)

### Version

0.0.33

### Device

Samsung Galaxy s9+

### Android version

10 (Stock)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Has to be a problem on your side, works fine on latest nightly.

**Comment by carbolymer** [comment]
How can I troubleshoot that?

**Comment by 1fexd** [comment]
You are using the latest nightly build right? If not, got to [LinkSheetNightly](https://github.com/1fexd/LinkSheetNightly/releases) and download the new relase. Set everything up like you did in the main app (settings export and import is coming soon), then try again. 

If it still does't work after trying, go to "Debug" -> "Logs" -> tap "Current session" -> then click "Export" and paste the logs here or send them via email to `1fexd@420blaze.it`

**Comment by kunalagra** [comment]
I faced similar issue on the latest nightly only on bit.ly and forms.gle links.

What fixed for me was to clear app data.

**Comment by 1fexd** [comment]
great!
