### ISSUE TITLE
Can't change preferred app

### ISSUE THREAD

**Issue by cycyx** [1fexd/LinkSheet#22]
In the parameter, once an app has been selected to always open an URL, you can't change it.

We should be able to change or erase a mistake.
Maybe a long tap or something?

I've got the issue with "UntrackMe": if I click on it, a bunch of checkboxes are unselected but not the URL set (by mistake).

**Comment by 1fexd** [comment]
Which url do you mean? Can you provide a screenshot?

**Comment by cycyx** [comment]
I'm in this situation: I've set up UntrackMe to always open 
koreus.com[https://koreus.com] (see screenshot).

There is no way to change that.

I would like to delete the association and use Vivaldi instead.

*De : *fe ***@***.***>
*À : *1fexd/LinkSheet ***@***.***>
*Cc : *cycyx ***@***.***>; Author 
***@***.***>
*Date : *2 mars 2023 10:10:50
*Objet : *Re: [1fexd/LinkSheet] Can't change preferred app (Issue #22)

**Comment by cycyx** [comment]
![Screenshot_2023-03-02-10-12-11-19_338d1168706d12c5c38fa9d3a60e24f4](https://user-images.githubusercontent.com/3910864/222394065-4b36fb20-0531-497b-be8b-309d6332eb4d.jpg)

If I click on UntrackMe, I can see a bunch of unchecked checkboxes (but not koreus.com) and no buttons.

**Comment by 1fexd** [comment]
Understood, will fix later

**Comment by 1fexd** [comment]
Can you check if release [0.0.18-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.18-debug) fixes this issue?

**Comment by cycyx** [comment]
It fixed my issue yes: I can see all the URLs handled by UntrackMe and the buttons to remove them all.
