### ISSUE TITLE
Incognito (Chrome) or Private Mode (Brave)

### ISSUE THREAD

**Issue by Samyak-Bumb** [1fexd/LinkSheet#222]
### Feature description

Add 1 more button to open the link in normal way or in incognito mode of the selected app example chrome, firefox, duckduckgo, brave etc.

**Comment by 1fexd** [comment]
What?

**Comment by 1fexd** [comment]
Settings -> Bottom sheet -> Enable "Request private browsing button"; Only supported in Firefox at the moment.
