### ISSUE TITLE
Preferred Browser doesn't work as expected

### ISSUE THREAD

**Issue by cycyx** [1fexd/LinkSheet#23]
In the settings, if you select a specific browser app or "always ask", the behavior is the same: it lists all the browsers.

**Comment by 1fexd** [comment]
I think there's an issue with saving settings, I can reproduce this when first opening the bottom sheet, but by the second time, it behaves as expected

**Comment by cycyx** [comment]
Never works for me: not the second time nor the 10th.

**Comment by 1fexd** [comment]
Will look into this later

**Comment by 1fexd** [comment]
I can reproduce this when I first open a link, close the bottom sheet, open settings, change the preferres browser, then re-open the link. Can you try force stopping the app after changing settings? That seems to work for me

**Comment by 1fexd** [comment]
Can you check if release [0.0.18-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.18-debug) fixes this issue?

**Comment by cycyx** [comment]
It changed the comportment: now I can see "native apps" and only the selected browser.

**Comment by 1fexd** [comment]
What exactly do you mean by that?

**Comment by 1fexd** [comment]
UntrackMe poses as a browser

**Comment by cycyx** [comment]
![Screenshot_2023-03-03-19-02-06-98_338d1168706d12c5c38fa9d3a60e24f4](https://user-images.githubusercontent.com/3910864/222794310-69d99dc5-cca5-456b-88ab-f8d15bb5e012.jpg)

Not in Linksheet.

**Comment by 1fexd** [comment]
Then it poses as a native app ;)
