### ISSUE TITLE
fix(1.0.0): Disable Facebook In-App browser

### ISSUE THREAD

**Issue by Yoanndp** [1fexd/LinkSheet#232]
### Bug description

Unable to Disable In-App Browser for Facebook App

####  Steps to Reproduce:
1. Open LinkSheet and disable In-App browser (Always disable).
2. Open the Facebook app and scroll down until you find a link.
3. Click on that link.
4. The Facebook app is still using its own In-App browser, despite disabling it in LinkSheet settings.

I am not sure if I understand the purpose of the In-App browser disabling feature correctly. If this behavior is intentional, could you please provide an explanation ?

### Version

0.0.33

### Device

Google Pixel 7

### Android version

Android 14

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
That's strange. I'll look into that when I have time

**Comment by 1fexd** [comment]
Okay, so I just checked this out and it appears like Facebook has built their **own** browser, meaning I can't really do anything about it, sorry.
