### ISSUE TITLE
fix(1.0.0): Browser does not open

### ISSUE THREAD

**Issue by nichu42** [1fexd/LinkSheet#234]
### Bug description

Trying to open a link from an email. But I don't get beyond the "Loading Link..." message. My browser does not open. 

### Version

LinkSheet Version Information:Built at (UTC): 2023-11-02 16:01:11 Flavor: Foss Type: nightly Commit: dfd2644 Branch: master Full identifier: master-dfd2644-nightly Build workflow ID: 6735086768

### Device

Samsung Galaxy Tab 6 Lite

### Android version

Android 13

### Application log or crash log

DIntentResolver
GetUri: Pre modification=https://foo.bar

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Can you please provide a full log (file)?

**Comment by nichu42** [comment]
Sorry for not getting back to you earlier. I played with some options and I have not come across that problem anymore. Will re-open if I find another e-mail link that doesn't work. Thanks so far.
