### ISSUE TITLE
Feature request: Hide specific browser apps

### ISSUE THREAD

**Issue by tatl-im** [1fexd/LinkSheet#24]
I have some apps on my phone that can be the default browser app, but I don't want to use them as a browser ever. I'd like to hide them from the browser list completely, without disabling or uninstalling.

E.g. PowerTube (ussr.razar.youtube_dl) is a YouTube video downloader app that can also be an all-purpose browser, but I never want to use it as a browser. I only use it to download videos. But every time I click ANY link, I see PowerTube in the list of browser apps. I never launch PowerTube by clicking on links.

I know there is a way to stop an app from opening specific links (e.g. stop the YouTube app from opening youtube.com links) but there is no way to exclude a general-purpose browser app from the list altogether. 

I like this app more than a few others I've tried, like Open Links With... (com.tasomaniac.openwith.foss) and Better Open With (com.aboutmycode.betteropenwith) but the feature of excluding specific browsers is one I miss. This can also be useful if people want to remove the built-in browser from the list, without disabling it, e.g. Chrome.

Thanks!

**Comment by 1fexd** [comment]
Hi, thanks for suggesting this feature. Can you check if release [0.0.19-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.19-debug) meets your expectations?

**Comment by tatl-im** [comment]
I love it, thank you so much!
