### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [1fexd/LinkSheet#25]
Is this option not available on Android 11?
https://github.com/1fexd/LinkSheet/blob/master/readme/screenshot5.png

No such option for me!

![Screenshot_20230303-124026_LinkSheet.png](https://user-images.githubusercontent.com/79910450/222654843-f86faa19-b8e4-4236-a72a-77b334abd401.png)

![Screenshot_20230303-124018_LinkSheet.png](https://user-images.githubusercontent.com/79910450/222654844-41de846f-68f7-4488-beff-804dc459f135.png)

**Comment by 1fexd** [comment]
No, this option is only available from Androi 12 onwards since that is when Google added the new domain verification system.

**Comment by Black-StellarSpectrum** [comment]
> No, this option is only available from Android 12 onwards since that is when Google added the new domain verification system.

Thanks 👍🏻
