### ISSUE TITLE
ClearURLs not working on Some Sites

### ISSUE THREAD

**Issue by RuthlessRuler** [1fexd/LinkSheet#256]
### Bug description

Some links like: https://analyticsindiamag.com/iit-bombay-joins-ibm-meta-to-form-ai-alliance-challenging-openai-google-amazon-microsoft/?utm_source=rss&utm_medium=rss&utm_campaign=iit-bombay-joins-ibm-meta-to-form-ai-alliance-challenging-openai-google-amazon-microsoft

Are not being cleaned by ClearURLs. Additionally, I have the suggestion to drop ClearURLs and use something like Adguard URL Tracking Protection and Actually Legitimate URL Shortner.

### Version

master-2762b87-nightly

### Device

Poco X3 Pro

### Android version

Android 13 (Stock)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks for discovering, this issue has been present for at least 4 months now lmao. Should be fixed in latest nightly.
