### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [1fexd/LinkSheet#26]
Please add an option to set dark mode theme as Amoled Black theme. Like for example a toggle in settings to turn ON amoled Black would be nice.

**Comment by 1fexd** [comment]
Please check release [0.0.21](https://github.com/1fexd/LinkSheet/releases/tag/0.0.21)

**Comment by Black-StellarSpectrum** [comment]
> Please check release [0.0.21](https://github.com/1fexd/LinkSheet/releases/tag/0.0.21)

It'd be nice if this were black themed as well.
![Screenshot_20230311-172535_LinkSheet.png](https://user-images.githubusercontent.com/79910450/224485898-e803c019-781d-4be4-af09-6823e2b99b74.png)

**Comment by 1fexd** [comment]
I wonder why it isn't, will look into this

**Comment by 1fexd** [comment]
Will be fixed in the next release.
