### ISSUE TITLE
Infinite Loading of Link with ClearURLs on Certain Links

### ISSUE THREAD

**Issue by RuthlessRuler** [1fexd/LinkSheet#267]
### Bug description

App went in infinite loading while loading this particular link: https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.washingtonpost.com%2Ftechnology%2F2023%2F12%2F13%2Ftesla-recall-autopilot%2F%3Fmc_cid%3D2a95ca7106%26mc_eid%3DUNIQID&data=05%7C02%7C%7C696427ed9dd24a71dd1108dbfc9eb177%7C961f23f8614c4756bafff1997766a273%7C1%7C0%7C638381530785410205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e3q5md214A8NGdW%2FbST9sLqfnJEKS2LZeYUONBFnH5s%3D&reserved=0

Note: The bug is triggered only with ClearURLs Turned On.

### Version

master-989b1f6-nightly

### Device

Poco X3 Pro

### Android version

Android 13

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks for reporting. Fixed in [1702580869](https://github.com/1fexd/LinkSheetNightly/releases/tag/1702580869)
