### ISSUE TITLE
LibRedirect instances out of date

### ISSUE THREAD

**Issue by brian6932** [1fexd/LinkSheet#275]
### Bug description

Release a new binary please. Also, it would be nice if you could set your own links as instances, like you can on the actual LibRedirect addon.

### Version

0.0.33

### Device

_

### Android version

_

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Please switch to nightly as described [here](https://github.com/1fexd/LinkSheet#nightly-builds). The next release still has some pending issues (https://github.com/1fexd/LinkSheet/milestone/1).

**Comment by brian6932** [comment]
@1fexd Hey sorry for the bump, but was wondering, how would I go about exporting from stable to nightly? Is the data the same, can I just do something like copy the files from `/data/app/*/fe.linksheet-*` to `/data/app/*/fe.linksheet.nightly-*` (without the apk)?
When searching root for the package name, this was all I found
![](https://github.com/1fexd/LinkSheet/assets/18603393/d9bce702-dd1a-4ea9-b1ba-b9ee3bd93b6d)

**Comment by 1fexd** [comment]
I have created a migrate build [here](https://github.com/1fexd/LinkSheet/releases/tag/0.0.34-migrate)
