### ISSUE TITLE
Add Better Support For Webapps

### ISSUE THREAD

**Issue by Tanmandal** [1fexd/LinkSheet#28]
There are webapps which do not have a default link opening setup please add the feature that their links could be opened in the webapp like a real app

**Comment by 1fexd** [comment]
What do you mean by web apps?

**Comment by Tanmandal** [comment]
I meant pwa 
Like in case of Amazon's web app there is only 1 verified link but amazon supports many other links
![Screenshot_2023-03-05-09-36-39-716_com android settings](https://user-images.githubusercontent.com/93572359/222941120-10de5a21-7834-4dcd-9bae-583511468f75.jpg)
Here in the pic you can see the amazon webapp supporting only 1 link but there are other links which it can cater and if such links are clicked on from within a browser , the webapp does gets opened

**Comment by 1fexd** [comment]
How did you create this PWA? I don't think adding any additional links is possible if you created the PWA from a browser app.

**Comment by Tanmandal** [comment]
In chromes latest  update pwas work just like apps and it is shown as a separate app as well
![Screenshot_2023-03-05-20-59-14-004_fe linksheet](https://user-images.githubusercontent.com/93572359/222969861-e32d3458-3af9-4d48-989c-9086bf73c60a.jpg)

**Comment by 1fexd** [comment]
What's your chrome version?

**Comment by Tanmandal** [comment]
![Screenshot_2023-03-05-22-03-46-026-edit_com miui securitycenter](https://user-images.githubusercontent.com/93572359/222973347-7b3c1330-fc4a-4a0b-8306-7f0596094a2f.jpg)

**Comment by 1fexd** [comment]
I am on the same version. I don't think it is possible since Chrome probably only registers this app as an url handler for the domain the PWA was created on.
