### ISSUE TITLE
Unshort Urls

### ISSUE THREAD

**Issue by HalfBloodprinc3** [1fexd/LinkSheet#283]
### Feature description

Add a function to see what is hidden behind the shorted urls.

**Comment by 1fexd** [comment]
So you want to see the long url first before opening? Because LinkSheet already supports skipping redirects.

**Comment by HalfBloodprinc3** [comment]
> So you want to see the long url first before opening? Because LinkSheet already supports skipping redirects.

Yes..now I understand.... sorry for the trouble

**Comment by 1fexd** [comment]
Great, can I close this then?
