### ISSUE TITLE
Support for Libredirect

### ISSUE THREAD

**Issue by HunterAPI** [1fexd/LinkSheet#29]
Is it possible to add support for Libredirect versions of websites?
https://libredirect.github.io

**Comment by 1fexd** [comment]
Yes, I am working on an implementation.

**Comment by HunterAPI** [comment]
You can implement something like this, where it lets you modify the URL parameters, but also add support for the path too, and ability to add more parameters. Also, have an option/drop down for domains that have a libredirect alternative, to apply that new domain?
I don't know tho, it might be too cluttered and not so user friendly. You can add an "advanced option" tab for it, maybe?

https://www.f-droid.org/packages/com.trianguloy.urlchecker/

**Comment by 1fexd** [comment]
I don't think it would be useful to replicate the functionality of other apps. You can always call those apps through LinkSheet.

**Comment by 1fexd** [comment]
Hi there, can you test release [0.0.23-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.23-debug) with experimental LibRedirect support? Thanks!

**Comment by 1fexd** [comment]
I made a new debug release which is less buggy: [0.0.24-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.24-debug)

**Comment by HunterAPI** [comment]
Seems to be working excellently.

**Comment by HunterAPI** [comment]
![screenshot](https://files.catbox.moe/mhjtcv.png)
Is this a bug?

Because I don't see it as an option here.
![screenshot](https://files.catbox.moe/afoxl3.png)

**Comment by HunterAPI** [comment]
![screenshot](https://files.catbox.moe/3vi5ya.png)

Make the link show the libredirected version for the apps that have it enabled.

**Comment by 1fexd** [comment]
> ![screenshot](https://camo.githubusercontent.com/89ec0a4bcabc4eb6e4ba95189c1f82f6c7c1326af906f5fc074cb7d46765d57b/68747470733a2f2f66696c65732e636174626f782e6d6f652f6d686a7463762e706e67) Is this a bug?
> 
> Because I don't see it as an option here. ![screenshot](https://camo.githubusercontent.com/fdc27cf0d212d1755c02b85ab1b95a1e12d73996924505a3147e294436338e00/68747470733a2f2f66696c65732e636174626f782e6d6f652f61666f786c332e706e67)

Yes, this is a bug in libredirect. I opened an [issue](https://github.com/libredirect/libredirect/issues/664)

**Comment by 1fexd** [comment]
I have fixed the bug. 

> ![screenshot](https://camo.githubusercontent.com/c6711ad5d3e8bb82842bbf61416402b822d148f88e5a9e3e29cfa3c2fffe3ba3/68747470733a2f2f66696c65732e636174626f782e6d6f652f3376693579612e706e67)
> 
> Make the link show the libredirected version for the apps that have it enabled.

Will look into this soon
