### ISSUE TITLE
fix(1.0.0): Preferred browser settings, the tick will disappear or appear (reverse selection)

### ISSUE THREAD

**Issue by cangling** [1fexd/LinkSheet#302]
### Bug description

bug:
Settings - Browser - Preferred Browser - Whitelist - Settings

After selecting a browser and swiping, the tick will disappear or appear (reverse selection) but not actually, go back to the top and enter it again and it will show selected or canceled normally.

### Version

master-346a601-nightly

### Previous version

0.0.34-migrate

### Device

redmi note 8

### Android version

10

### Application log or crash log

Settings - Browser - Preferred Browser - Whitelist - Settings

After selecting a browser and swiping, the tick will disappear or appear (reverse selection) but not actually, go back to the top and enter it again and it will show selected or canceled normally.

Example Application 1DM Browser

https://github.com/1fexd/LinkSheet/assets/7885420/71d63f6c-6bfc-4130-9dfa-77a07a9a71f0

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Fixed in the latest nightly build.
