### ISSUE TITLE
feature(1.0.0): Swap out embed service URLs with the original URL

### ISSUE THREAD

**Issue by Vodes** [1fexd/LinkSheet#309]
### Feature description

Services like fxtwitter.com are great in telegram/discord and other chatting apps to have proper embeds but they require a redirect either with a browser or this app. We could possibly avoid this by swapping the URLs with one that the native app of each service can open.

I have collected a bunch of embed services and would definitely appreciate if others could chip in, in case I forgot some.

```
Twitter

*.vxtwitter.com
*.fxtwitter.com

X (maybe it's better to convert those to x.com links?)

*.fixvx.com
*.fixupx.com

Tiktok (-> tiktok.com)

*.tiktxk.com
*.vxtiktok.com
*.tnktok.com

Reddit (-> reddit.com)

*.rxddit.com
*.rxyddit.com

Twitch (-> twitch.tv)

*.txitch.tv  

Instagram (-> instagram.com)

*.ddinstagram.com

Pixiv (-> pixiv.net)

*.phixiv.net
```

In the case of `*.` it should prepend that subdomain to the original aswell.
For example:
`https://old.rxddit.com/r/linux_gaming/comments/1ahuh8p` should go to<br> `https://old.reddit.com/r/linux_gaming/comments/1ahuh8p`
`https://clips.txitch.tv/KathishNaivePineappleOSfrog-cSa6o0V7gy7c-cZR` should go to<br> `https://clips.twitch.tv/KathishNaivePineappleOSfrog-cSa6o0V7gy7c-cZR`

(the latter doesn't even work anymore but all the more reason to swap it)

**Comment by 1fexd** [comment]
There aren't any such services for Facebook as far as I'm aware - but if you know such services you can suggest them
