### ISSUE TITLE
Preferred Apps

### ISSUE THREAD

**Issue by HunterAPI** [1fexd/LinkSheet#32]
Can you add the ability to set domains to always open, without having to go through the link sheet?

![screenshot](https://files.catbox.moe/0f37vm.png)

**Comment by 1fexd** [comment]
I have implemented this in release [0.0.26-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.26-debug), can you test it?

**Comment by HunterAPI** [comment]
> I have implemented this in release [0.0.26-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.26-debug), can you test it?

Works, thanks.
