### ISSUE TITLE
feat(links): Don't pass URLs to external services based on keywords/regex/domains

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [1fexd/LinkSheet#329]
### Feature description

Issue: Sometimes you would encounter darknet sites such as *.onion and *.i2p. Passing them to amp2html (and similar services) would not only cause an error, but also defeat the whole point of darknet to be anonymous.

Suggestion: Add an (potentially customizable) exclusion to the URL handler section.

**Comment by SodaWithoutSparkles** [comment]
Actually you do want to remove tracking parameter (if that exist) to improve privacy. Just don't pass it to external services would be fine.

**Comment by 1fexd** [comment]
Yes, thanks!
