### ISSUE TITLE
A better and easier UX.

### ISSUE THREAD

**Issue by not-programmer98** [1fexd/LinkSheet#33]
It will be easier if you make the most used browser (this that have buttons justonce and always) in the bottom near the finger, Also I wish if there's an option to fix a certain browser on the bottom.
So the expected behavior is once I click a link the browser that I choosed will be at the bottom near my finger with all buttons ( share, cooy, always, just once) then the other options above

**Comment by not-programmer98** [comment]
Or at least it will be good if you add an option to choose a fixed browser 
![IMG_20230306_213016](https://user-images.githubusercontent.com/126913926/223211645-402d442d-2512-44bb-8d67-65d86847dcab.jpg)
I want to fix Bromite to appear in the top every time ( since it's the most one that I use) instead of show the last used one.
I hope you get me because my English is bad

**Comment by 1fexd** [comment]
Have you enabled usage stats in settings? It should then be sorted by usage stats, and then move Bromite to the top. You can also choose a single browser in `Apps` -> `Preferred browser`

**Comment by not-programmer98** [comment]
I mean I want a fixed browser in bottom near finger that doesn't change its location and other options above because I didn't use them that much.

**Comment by not-programmer98** [comment]
Yes, exactly.

**Comment by HunterAPI** [comment]
> Okay so you want to set a browser that's always at the same position in the bottom sheet?

Do you mean like having a fixed order for the whitelisted apps that we can rearrange? I think that would be very useful.

**Comment by 1fexd** [comment]
Related: #106. If you need anything else, please open a new issue.
