### ISSUE TITLE
copy/share button didn't show when preview urls is off

### ISSUE THREAD

**Issue by l2eused** [1fexd/LinkSheet#333]
### Bug description

when **preview URL** is disable, can't copy/share url. it should showing even if preview urls is disable.

edited: I don't know if you prefer this occur or not. you can close this if you think it work normally

### Version

0ef7d15

### Device

Xiaomi Mi9

### Android version

Android 13

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
This is intentional.
