### ISSUE TITLE
fix(1.0.0): "Verified link handlers" doesn't link to correct settings page in One UI

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#338]
### Bug description

I think we talked about this before in that issue thread that became incredibly long, but since the behavior is still happening, I figured it's worth having its own issue to track it.

Rather than going directly to an app's "Set as default" page (as it's called in One UI), tapping (or long pressing wt Shizuku mode) on an app in the "Verified link handlers" settings lead to the page one level up called "Apps that can open links".

### Version

LinkSheet Version Information: Built at (UTC): 2024-03-07 14:05:57 Flavor: Foss Type: nightly Commit: 9f65588 Branch: master Full identifier: master-9f65588-nightly Build workflow ID: 8194121941

### Device

Fold5

### Android version

Android 14 (One UI 6)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Yeah I remember, this is Samsung specific (https://stackoverflow.com/a/72365164) - not sure if it has been fixed yet, will check later.

**Comment by 1fexd** [comment]
Works on A14/OneUI6, workaround removed

**Comment by 1fexd** [comment]
#346
