### ISSUE TITLE
Broken WebApps

### ISSUE THREAD

**Issue by dariusz-goc** [1fexd/LinkSheet#339]
### Bug description

Opening WebApps like Twitter Lite result in showing of the bottom sheet in a loop. If I choose the WebApp from the bottom sheet to be opened the sheet is displayed again, if I choose a browser a custom chrome tab is opened. There is no way to display the web app as a native app without the browser interface.

My default chosen browser is Chrome. I tried setting Twitter Lite as the default app for opening links, but the bottom sheet loop has not resolved.

### Version

master-d4cd3ea-nightly

### Device

Xiaomi Mi 9T Pro

### Android version

Android 14

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Should be fixed now, could you please confirm?

**Comment by dariusz-goc** [comment]
Twitter Lite still looping. Here's the app in question:
https://www.apkmirror.com/apk/twitter-inc/twitter-lite-2/twitter-lite-2-3-1-1-release/

**Comment by dariusz-goc** [comment]
Closed by mistake

**Comment by 1fexd** [comment]
Strange, for me Twitter Lite works - could you please attach a log + preferences export?

**Comment by dariusz-goc** [comment]
First can you point me to a version of link sheet that works for you? I tried latest nightly

**Comment by dariusz-goc** [comment]
I downloaded latest version from actions tab, the one that was still building while I downloaded latest nightly from the readme link. Now Twitter Lite opens 👏 however there is still browser UI showing on top. I don't believe it was there prior. It looks like a Chrome custom tab.

**Comment by dariusz-goc** [comment]
Nevermind, it's the same with Chrome as the default browser and on my other devices without LinkSheet. Consider it fixed 😂
