### ISSUE TITLE
Replace the native share menu with linksheet

### ISSUE THREAD

**Issue by venkat2305** [1fexd/LinkSheet#34]
1. Can you add an option to remove the native share with the link sheet. The native share menu on miui is shitty and link sheet has amazing features like clear url and fast forward. 

2. Also, is it possible to notify, keep history when clear urls , fast-forward features were used.

Thank you so much for this app

**Comment by 1fexd** [comment]
> 1. Can you add an option to remove the native share with the link sheet. The native share menu on miui is shitty and link sheet has amazing features like clear url and fast forward.

That won't be possible, especially without root.



> 2\. Also, is it possible to notify, keep history when clear urls , fast-forward features were used.

What do you mean by that?

**Comment by venkat2305** [comment]
2. Whenever tracking parameters are removed from a url, it should maintain a record of it. Similarly for fast forward. Notification also would be great.
Does this make sense?

**Comment by 1fexd** [comment]
Ah, ok, now I understand. I will check if this is feasable.

**Comment by 1fexd** [comment]
I don't think it is necessary to maintain a record of every time ClearURLs or FastForward is invoked. Also, I think a Toast message for every invokation of said integrations would just be a lot of unnecessary clutter.

**Comment by venkat2305** [comment]
The main issue is , sometimes we need to have some parameters in the link to reach the destined website. So,It would be good to know if there were any modifications.

**Comment by 1fexd** [comment]
> > I don't think it is necessary to maintain a record of every time ClearURLs or FastForward is invoked. Also, I think a Toast message for every invokation of said integrations would just be a lot of unnecessary clutter.
> 
> Maybe time for a debug menu with optional toggles for power users. Or even just a logging mode that writes to an easily accessible file.

I'm not sure this is really necessary

**Comment by venkat2305** [comment]
Just maintain a record when any modifications were made to the url

**Comment by 1fexd** [comment]
Related issue #91, implementation will take place there.
