### ISSUE TITLE
Dont attempt to download files

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [1fexd/LinkSheet#342]
### Bug description

Linksheet would attempt to download the file if a link points to it. This is not desirable as the resulted link might not work and the file would be downloaded twice.

### Version

11993ed-nightly

### Device

Poco x4 gt

### Android version

a13, miui 13

### Reproducible on latest nightly build

Yes

**Comment by SodaWithoutSparkles** [comment]
Steps to reproduce:

1. Install and login to Github mobile
2. Set linksheet as default browser
3. Navigate to Linksheet nightly or any other repo with an apk release
4. If available, enable the network speed status widget in system settings
5. Attempt to download the file, Linksheet loads for abnormally long and the network status showed download activity
6. Repeat with linksheet not as dafault browser

**Comment by 1fexd** [comment]
I can't reproduce this issue, could you please provide the log/preferences and a screen recording if possible?

**Comment by SodaWithoutSparkles** [comment]
https://github.com/1fexd/LinkSheet/assets/64138578/d7d94355-63f8-4376-9289-c48de9345f92

Video sped up by 3x to reduce size

**Comment by SodaWithoutSparkles** [comment]
Another possible clue is the data usage. 

1. Find network data transfered by app stats on your phone
2. Go to the github repo mentioned above and fetch a few of the different release versions, but dont click through it
3. Go back to step 1 and the usage rate significantly increased. For examlple, LinkSheet shouldn't use 87.8MB in 1 hour.

**Comment by 1fexd** [comment]
Please try again using the latest build

**Comment by SodaWithoutSparkles** [comment]
Master at a026a91 have not fix the problem.

Also, I noticed that, if i close linksheet when it was fetching/downloading, it still loads in background as shown by the network activity. Should I open another issue?

**Comment by 1fexd** [comment]
Please send another log

**Comment by SodaWithoutSparkles** [comment]
[The bin](https://pastebin.com/i6n6GujV)

Since my WiFi at home is much faster, I dont have enough time to reproduce the "still downloading after 'quitting' " issue.

**Comment by SodaWithoutSparkles** [comment]
Ah ha it seems that we might be onto something. I pressed the "share" button next to download, send it to curl amd this happened:

![Screenshot_com.termux-edit.jpg](https://github.com/1fexd/LinkSheet/assets/64138578/a1861900-5da4-4bac-acaa-0954640e7d72)

These are the response headers:

```
HTTP/2 200
content-type: application/vnd.android.package-archive
content-md5: shSmH8k3gywlyxBtiify7A==
last-modified: Sat, 09 Mar 2024 03:55:41 GMT
etag: "0x8DC3FECCA2FC722"
server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 22ab3228-001e-0048-59d5-71fc62000000
x-ms-version: 2020-10-02
x-ms-creation-time: Sat, 09 Mar 2024 03:55:41 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
content-disposition: attachment; filename=revanced-manager-v1.19.2.apk
x-ms-server-encrypted: true
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 1590
date: Fri, 15 Mar 2024 15:07:16 GMT
x-served-by: cache-iad-kjyo7100029-IAD, cache-nrt-rjtf7700025-NRT
x-cache: HIT, HIT
x-cache-hits: 1083, 0
x-timer: S1710515237.623915,VS0,VE160
content-length: 44012426
```

Especially the following headers:

```
content-type: application/vnd.android.package-archive
content-length: 44012426
```

It seems that linksheet didnt recognize that it was downloading a file?

**Comment by 1fexd** [comment]
Finally managed to reproduce it, thanks! Should be fixed now, could you please confirm?

**Comment by SodaWithoutSparkles** [comment]
From my brief experiment this should be fixed in latest nightly.
