### ISSUE TITLE
Crashing Bug

### ISSUE THREAD

**Issue by HunterAPI** [1fexd/LinkSheet#35]
When I tried visiting a link with more than 1 "hashtag" it crashes. The number of hashtags doesn't matter as long as it's  >=2, to reproduce the bug.

Examples of URLs: 
https://example.com/##
https://example.com/#x#
https://example.com/x##
https://example.com/#xxxxxxxxxx#

Edit:
This seems to only be crashing when I use the ClearURLs implementation. I checked one at a time for all of the options, and ClearURLs is the only one breaking.

**Comment by 1fexd** [comment]
Should be fixed in [0.0.27-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.27-debug)
