### ISSUE TITLE
Some issues in the latest nightly

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#352]
### Bug description

I'm not sure if these behaviors were introduced with the most recent nightly, or if they originate from one of the others released in the past few hours, but several versions ago, after the new experimental URL bar was added, all it did was add the share button under it, but a copy button was still present on the bar. Now, when the new toggle for the experimental bar is enabled, the copy button isn't accessible at all. Furthermore, the site preview option now only works if the experimental bar is enabled.

![Screenshot_20240316_043431_LinkSheet Nightly](https://github.com/1fexd/LinkSheet/assets/25999169/1dd8abca-8aa7-4822-9f75-92ce924e4d0c)
![Screenshot_20240316_043441_LinkSheet Nightly](https://github.com/1fexd/LinkSheet/assets/25999169/3822cee4-c9d7-446a-9e58-0d65dd7077c6)

### Version

LinkSheet Version Information: Built at (UTC): 2024-03-16 03:36:46 Flavor: Foss Type: nightly Commit: 972bfa7 Branch: master Full identifier: master-972bfa7-nightly Build workflow ID: 8306563902

### Device

Fold5

### Android version

Android 14 (One UI 6.0)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks for the report, I'm still actively working on this feature so it's excepted that certain things don't work / are not implemented - no need to report them here - I'll make this more clear in the app and in the bug report tempaltes.

A better place for feedback would be [Discord](https://discord.gg/XndZet2pWF) (or some other form of instant messaging).
