### ISSUE TITLE
An option for in-app Amoled Black theme to follow system theme accordingly, not be permament

### ISSUE THREAD

**Issue by Username1-a** [1fexd/LinkSheet#353]
### Feature description

Basically,
System Light theme > In-app Light theme
System Dark theme > In-app Amoled Black theme

As of now, in-app Amoled Black theme stays permament, even when system light theme is on, so such option would be appreciated to keep things consistent

Thank you for your app

![Screenshot_20240316-131755_LinkSheet](https://github.com/1fexd/LinkSheet/assets/47947180/f9f9a79e-75c8-46cb-aeae-949c55b85e54)

**Comment by SodaWithoutSparkles** [comment]
So something like this?

- System (Light/Dark)
- System (Light/Amoled Dark)
- Light
- Dark
- Amoled Dark

**Comment by SodaWithoutSparkles** [comment]
> > Three settings:
> > 
> > - Light/Dark/System
> > - Use Martial You theme: Yes/No (Toggle)
> > - Dark is AMOLED: Yes/No (Toggle)

You may want to future proof this in case you want to add more themes.

- Follow system theme (True/False)
- Use Material You theme (True/False)
- Light mode is (dropdown): Light
- Dark mode is (dropdown): Dark/amoled

**Comment by 1fexd** [comment]
I've reworked the theme screen (as I am also overhauling the whole app UI) and added toggles for Dynamic color/Material You as well as Pure Black/Amoled
