### ISSUE TITLE
Sending anything to LinkSheet causes crash

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#354]
### Bug description

As of the latest nightly, LinkSheet appears to be completely broken and crashes when called from open or share dialogs.

### Experiments

- [X] I have disabled all experiments

### Version

LinkSheet Version Information: Built at (UTC): 2024-03-16 17:38:07 Flavor: Foss Type: nightly Commit: 1de6c07 Branch: master Full identifier: master-1de6c07-nightly Build workflow ID: 8310928110

### Device

Fold5

### Android version

Android 14 (One UI 6.0)

### Application log or crash log

{
  "device_basics": {
    "android_version": "14",
    "locale": "en-US"
  },
  "device_info": {
    "manufacturer": "samsung",
    "model": "SM-F946U1",
    "fingerprint": "samsung/q5quew/q5q:14/UP1A.231005.007/F946U1UES2BXBE:user/release-keys"
  },
  "app_info": {
    "full_identifier": "master-1de6c07-nightly",
    "built_at": "2024-03-16 17:38:07",
    "commit": "1de6c07",
    "branch": "master",
    "flavor": "Foss",
    "type": "nightly",
    "workflow_id": "8310928110"
  },
  "active_experiments": [],
  "preferences": [
    {
      "name": "hide_after_copying",
      "value": "true"
    },
    {
      "name": "usage_stats_sorting",
      "value": "true"
    },
    {
      "name": "browser_mode",
      "value": "AlwaysAsk"
    },
    {
      "name": "selected_browser",
      "value": "<null>"
    },
    {
      "name": "in_app_browser_mode",
      "value": "AlwaysAsk"
    },
    {
      "name": "selected_in_app_browser",
      "value": "<null>"
    },
    {
      "name": "unified_preferred_browser",
      "value": "true"
    },
    {
      "name": "in_app_browser_setting",
      "value": "UseAppSettings"
    },
    {
      "name": "always_show_package_name",
      "value": "true"
    },
    {
      "name": "url_copied_toast",
      "value": "true"
    },
    {
      "name": "download_started_toast",
      "value": "true"
    },
    {
      "name": "opening_with_app_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_failed_toast",
      "value": "true"
    },
    {
      "name": "grid_layout",
      "value": "true"
    },
    {
      "name": "use_clear_urls",
      "value": "true"
    },
    {
      "name": "fast_forward_rules",
      "value": "true"
    },
    {
      "name": "enable_lib_redirect",
      "value": "false"
    },
    {
      "name": "follow_redirects",
      "value": "false"
    },
    {
      "name": "follow_redirects_local_cache",
      "value": "true"
    },
    {
      "name": "follow_redirects_external_service",
      "value": "false"
    },
    {
      "name": "follow_only_known_trackers",
      "value": "false"
    },
    {
      "name": "follow_redirects_builtin_cache",
      "value": "true"
    },
    {
      "name": "follow_redirects_allow_darknets",
      "value": "false"
    },
    {
      "name": "theme",
      "value": "3"
    },
    {
      "name": "dont_show_filtered_item",
      "value": "true"
    },
    {
      "name": "use_text_share_copy_buttons",
      "value": "false"
    },
    {
      "name": "preview_url",
      "value": "true"
    },
    {
      "name": "enable_downloader",
      "value": "true"
    },
    {
      "name": "downloaderCheckUrlMimeType",
      "value": "false"
    },
    {
      "name": "enable_ignore_lib_redirect_button",
      "value": "true"
    },
    {
      "name": "follow_redirects_timeout",
      "value": "15"
    },
    {
      "name": "enable_amp2html",
      "value": "true"
    },
    {
      "name": "amp2html_local_cache",
      "value": "true"
    },
    {
      "name": "amp2html_external_service",
      "value": "false"
    },
    {
      "name": "amp2html_builtin_cache",
      "value": "true"
    },
    {
      "name": "amp2html_allow_darknets",
      "value": "false"
    },
    {
      "name": "enable_request_private_browsing_button",
      "value": "false"
    },
    {
      "name": "show_as_referrer",
      "value": "false"
    },
    {
      "name": "dev_mode_enabled",
      "value": "false"
    },
    {
      "name": "first_run",
      "value": "true"
    },
    {
      "name": "show_discord_banner",
      "value": "false"
    },
    {
      "name": "use_dev_bottom_sheet",
      "value": "false"
    },
    {
      "name": "donate_card_dismissed",
      "value": "true"
    },
    {
      "name": "dev_bottom_sheet_experiment",
      "value": "true"
    },
    {
      "name": "resolve_embeds",
      "value": "false"
    },
    {
      "name": "hide_bottom_sheet_choice_buttons",
      "value": "true"
    },
    {
      "name": "last_version",
      "value": "1710628687"
    }
  ],
  "log": [
    {
      "type": "Crash",
      "time": "2024-03-16T18:31:49.966",
      "message": "<not_included>"
    }
  ]
}

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
4bc5badc4eb82e1b362d3436b0ae0af67e35320b
