### ISSUE TITLE
Incorrect LinkSheet Pro description

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [1fexd/LinkSheet#355]
### Bug description

The donate banner currently says: 

> [...] only hides the donation banner on the main screen of the app

Which is incorrect. LinkSheet Pro currently also offers some superbase API features like non-amp redirect and external redirect 

Relevant strings: 

https://github.com/1fexd/LinkSheet/blob/1de6c07a102cf2f4083bc4d987d68e78050949ed/app/src/main/res/values/strings.xml#L449-L452

### Experiments

- [X] I have disabled all experiments

### Version

ccf8039

### Device

Poco x4 gt

### Android version

a13, miui13

### Reproducible on latest nightly build

Yes

**Comment by SodaWithoutSparkles** [comment]
This looks like a simple fix that I could PR.

**Comment by 1fexd** [comment]
Sure
