### ISSUE TITLE
"Apps which can open links" list is incomplete.

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#36]
On my device, it only shows 105 apps. The system "Apps that can open links" page in settings shows 203. Though that page _does_ include apps I have installed on all 4 profiles (Main/Dual/Work/Secure) those apps alone are nowhere near enough to make up for the almost 100 app difference.

Also some of the app names and icons are wonky, and the list is sorted A-Z,a-z rather than A/a-Z/z so "eBay" is listed last for instance.

**Comment by 1fexd** [comment]
I can't reproduce the first issue since I don't have a secondary profile, but I guess the issue is that LinkSheet only shows apps from your main profile which have a launcher activity (i.e. it shows up as an app in your app drawer). 

I have fixed the sorting issue.

**Comment by 1fexd** [comment]
Strange, Gmail and FedEx show up for me (FV File Explorer and F-Droid won't, since they have no verified app links). If I sent you a debug build, would you be able to do a logcat?

**Comment by 1fexd** [comment]
I don't know of any tools, I just use `adb`; Do you have access to a PC with `adb`?

**Comment by 1fexd** [comment]
Okay, I have uploaded a debug build here: [0.0.28-debug](https://github.com/1fexd/LinkSheet/releases/tag/0.0.28-debug). This app installs next to the release build, so you will need to set it as default browser. 

To get the logcat, first execute `adb shell pidof -s fe.linksheet.debug` which yields the process id of the app, then run `adb logcat --pid=YOUR_PID_HERE`. After that, open the "Apps which can open links" settings page, which should print lots of lines containing `D InstalledPackage:`. Find the ones of the apps you don't see on the settings page, then check what it says after the second `:`. If it says `null`, the package could somehow not be resolved/or it has no user-facing app. If there is no line for the apps you are missing, the package could (for some reason) not be found.

Example line where the app is resolved correctly: 

`03-17 16:20:13.950 29807 31366 D InstalledPackage: com.google.android.GoogleCamera: ResolveInfo{81be52a com.google.android.GoogleCamera/com.android.camera.CameraLauncher m=0x108000}`

Example line where it isn't / there is no user-facing app:`03-17 16:20:13.953 29807 31366 D InstalledPackage: com.google.android.inputmethod.latin: null`

**Comment by 1fexd** [comment]
> I see a potential problem here. Both `com.samsung.android.mobileservice` and `com.samsung.android.mateagent` show up as `null` (and therefore aren't listed in LinkSheet), and I suspect this is due to them not having user-facing apps. However they are both able to handle links and each have a few listed under `Supported web addresses`.

Damn, I didn't take that into account. 

> Interestingly, `com.samsung.android.mobileservice` _is_ shown in 0.0.22, as you can see in the screenshot above, but in the debug version, it's gone.

Yep, I changed the behavior in `0.0.23`. The strange thing is that I actually added a fallback to the old version, should an app not have a user-facing launcher

**Comment by 1fexd** [comment]
Yes, FV and F-Droid show up in the system menu on my phone, but not in LinkSheet (expected behavior since FV does not have any links, while F-Droid has some but they must be selected by the user). I am not quite sure how to fix this, I think it may be a OneUI bug since it works flawlessly on stock android.

**Comment by 1fexd** [comment]
> I'm confused. Are you on stock? If FV (with no links) is showing up on your system menu, then isn't stock having the same issue?

Isn't the issue that Gmail and those Samsung apps do not show up in LinkSheet?



> Also, do you mean that the links for F-Droid are not enabled by default but the user is able to select them from the system menu? If that is the case, shouldn't F-Droid still show up in LinkSheet (under disabled by default), in case it was enabled at some point?

Yes, I have fixed this.

**Comment by 1fexd** [comment]
> apps with no UI now

Stange, this still shouldn't happen. Will check again

**Comment by 1fexd** [comment]
> Just installed 0.0.29 and quite a few apps with user selectable links (and some with both) are still not shown, in addition to the apps mentioned in previous comments. These include:
> 
>     * `com.authy.authy`
> 
>     * `com.joaomgcd.autoshare`
> 
>     * `com.joaomgcd.autotools`
> 
>     * `com.cardpointers.app`
> 
>     * `com.samsung.android.themestore`
> 
>     * `com.samsung.android.gts`
> 
>     * `com.lifx.lifx`
> 
>     * `com.microsoft.appmanager`
> 
>     * `com.google.audio.hearing.visualization.accessibility.scribe`
> 
>     * `org.schabi.newpipe`
> 
>     * `net.ssens.headsupa`
> 
>     * `com.samsung.android.app.sharelive`
> 
>     * `com.vanced.android.youtube`/`app.revanced.android.youtube`/`app.rvx.android.youtube`
> 
>     * `nl.fameit.rotate`
> 
>     * `com.samsung.android.app.spage`
> 
>     * `com.sec.android.app.shealth`
> 
>     * `com.samsung.android.shealthmonitor`
> 
>     * `com.samsung.android.tvplus`
> 
>     * `com.samsung.android.fast`
> 
>     * `org.telegram.messenger`
> 
>     * `org.thunderdog.challegram`
> 
>     * `com.ss.android.ugc.trill` (but `com.zhiliaoapp.musically` does show up)
> 
>     * `com.tmobile.tuesdays`
> 
>     * `com.ups.mobile.android`
> 
>     * `com.vanced.manager`
> 
>     * `us.zoom.videomeetings`

At the moment, apps with user selectable links will only show up if at least one of the links has been selected by the user.

**Comment by 1fexd** [comment]
> Found the following apps in the system menu which also don't appear in LinkSheet (and have links that are _not_ user-selectable):
> 
>     * Google Play Services
> 
>     * Link to Windows
> 
>     * Meta App Manager
> 
>     * Quick share
> 
>     * Samsung accounts
> 
>     * Samsung wallet digital key
> 
> 
> There are also some more packages with no user-facing apps that _do_ have user-selectable links like Google Play Services for AR.
> 
> Also, interestingly enough, LinkSheet (both stable and debug) is one of those apps that show up in the system menu despite not having any supported links at all.

Will look into that.

**Comment by 1fexd** [comment]
Very strange, I just tested `Link to Windows` and it shows up just fine in LinkSheet

**Comment by 1fexd** [comment]
Sorry for getting back to you this late, does this issue still persist on the [latest nightly build](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip)?

**Comment by 1fexd** [comment]
> I didn't check every app one by one because for some reason, all the apps are out of order in the nightly (YouTube was second on the list lol)

Fixed.

> It seems the spacing was also changed? Went from about 19 apps per page to 17.

Yes, but that's probably going to change again. 

I am starting to think this is some sort of bug in OneUI? Everything works fine here on my Pixel. [Wouldn't be the first time I had to specifically work around Samsung's buggy software lol](https://github.com/1fexd/LinkSheet/blob/f7fdb37bfcf4b39c16c93129a850e044bab84592/app/src/main/java/fe/linksheet/module/viewmodel/AppsWhichCanOpenLinksViewModel.kt#L50)

**Comment by 1fexd** [comment]
> Also was it intended that the share sheet's show package name setting also affects the "apps which can open links" list?

Yes, gonna move the switch somewhere else, thanks for pointing that out.

> A bit unrelated, but there could be some further clarity on the "use unified settings" option (and the two buttons under it). Played around with it for 10 min and could not figure out what it does lol

Will do.

**Comment by 1fexd** [comment]
Alright, the "Use unified settings" toggle has a clear description now. Switch will be moved somewhere else in 1.0.0 (see #140), marked with a disclaimer for now.

**Comment by 1fexd** [comment]
If there's still anything left that to fix, please open a new issue. This one's getting quite long and is filled with unrelated stuff. Thanks :)
