### ISSUE TITLE
Remove top (always/just once) section

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#38]
This is very much a personal thing, but as someone who sets little to no defaults, I always hated that whatever my most used/top pick app became, I was forced to interact with the open menu differently to use it than other apps (having to press "just once", having to avoid accidentally pressing "always", and then having to dig through settings to unser it if I did; rather than just being first in the list and easily double tapping it to open with no risk).

The option to remove this section altogether would be a welcome addition.
![SmartSelect_20230314_060556_LinkSheet](https://user-images.githubusercontent.com/25999169/224985685-2df4f5b5-0bc1-4590-b984-daf3a948acea.jpg)

**Comment by 1fexd** [comment]
Will be implemented in the next release.
