### ISSUE TITLE
Add the blacklist feature

### ISSUE THREAD

**Issue by xmha97** [1fexd/LinkSheet#39]
Please add the blacklist feature.
Some sites open automatically.
I want to block them.

I need a settings page to add some website.
Then prevent the LinkSheet popup menu for them.

Thanks

**Comment by 1fexd** [comment]
I don't understand what you mean. When does this issue occur?

**Comment by xmha97** [comment]
Hi, sorry for the delay in the answer
Some VPNs, like Psiphon, open a promotional site after connecting to the server, I want to block these sites.

The mechanism is that an app wants to open a site, but Linksheet stops it and nothing happens.

(Sorry for my bad English)

**Comment by 1fexd** [comment]
I think this is out of scope, maybe you should ask the devs to remove (or allow the user to disable) that "feature".
