### ISSUE TITLE
Where to donate?

### ISSUE THREAD

**Issue by dgudim** [1fexd/LinkSheet#4]
It's a really usefull app, I want to support the development, where do I donate?

**Comment by 1fexd** [comment]
Hi thanks, a lot! Do you have some crypto by any chance? Sadly, it's not gonna be possible otherwise

**Comment by dgudim** [comment]
I have like 3$ worth of Ethereum, but I can't really buy it in my country. But still, just put your wallet address in the readme, when someone pays me in crypto, I'll donate.
