### ISSUE TITLE
[Issue] Some native apps are not shown 

### ISSUE THREAD

**Issue by Terkyz** [1fexd/LinkSheet#44]
Applications such as Libretube (Youtube), Megalodon (Mastodon), Nekogram X (Telegram) are not displayed as options when opening a link, but the default browser (at LinkSheet, who is already the default browser of the system) is open automatically.

 [Here](https://imgur.com/a/RSsJf6o), a demonstrative video

**Comment by 1fexd** [comment]
Does that only happen in Telegram? What's your Android version?

**Comment by Terkyz** [comment]
No, it happens in all "native" applications, and I put "native" in quotation marks because some like Libretube even if it supports and redirects Youtube links, it is not directly "native".

I'm on Android 11

**Comment by BhaturaGuy** [comment]
Same issue here. Link sheet doesn't show Revanced apps, FOSS apps. It just shows some common apps only.
Nightly release retains this bug

**Comment by 1fexd** [comment]
Can you provide a list of apps which are not shown, but should be, so I can try to debug that?

**Comment by 1fexd** [comment]
Closing this for now as it has been stale for a bit. Please open a new issue if the problem persists.

**Comment by RuthlessRuler** [comment]
Works for me.
LibreTube is correctly shown when opening YouTube Links.
