### ISSUE TITLE
[issue] "Apps which can open links" section

### ISSUE THREAD

**Issue by 0uros** [1fexd/LinkSheet#47]
Hi there, I am testing the app and I have noticed an error with my device, when trying to see the links that an application manages, the app crashes, [I leave you a link](https://imgur.com/a/o42bgGF).

I have a Samsung Galaxy S10, with Android 12, Oneui 4.1

**Comment by 1fexd** [comment]
Can you provide a logcat?

**Comment by 0uros** [comment]
How can I send a logcat?

**Comment by 1fexd** [comment]
Yes, run `adb shell pidof -s fe.linksheet` (on windows you need to use `adb.exe`) which yields a PID. After that, run `adb logcat --pid=YOUR_PID_HERE`, then do the thing that crashed the app and send the log here

**Comment by 0uros** [comment]
I tried the first command but it doesn't seem to do anything
![image](https://user-images.githubusercontent.com/67289586/229332519-cb75a598-8dcb-4b6a-8492-eb31095308fb.png)

**Comment by 1fexd** [comment]
The app must be running

**Comment by 0uros** [comment]
For some reason it didn't generate a file, so I manually copied everything it did and pasted it, here is the log.
[log.txt](https://github.com/1fexd/LinkSheet/files/11139688/log.txt)

**Comment by 1fexd** [comment]
Sorry, I didn't properly explain, you need to start the logcat, then do what you originally did to trigger the crash for me to be able to debug it.

**Comment by 0uros** [comment]
If, I have done that, the application suddenly closes, but does not generate a file to send, should I run one more command?

**Comment by 1fexd** [comment]
> but does not generate a file to send

What do you mean by that? Is there no log in logcat?

**Comment by 0uros** [comment]
Sure, it doesn't generate a logcat, the app closes, new information stops appearing in the console (only the one that was there before the crash) but it doesn't generate the file. What is on the screen I sent you in the other message

**Comment by 1fexd** [comment]
That's very strange. Sadly, since I don't have Samsung device, I won't be able to debug this one without any error message whatsoever.

**Comment by 1fexd** [comment]
Fixed in #72.
