### ISSUE TITLE
[Bug] Stuck at loading link

### ISSUE THREAD

**Issue by not-programmer98** [1fexd/LinkSheet#48]
When I'm trying to open some links, the app stuck at loading link
![Imagepipe_0](https://user-images.githubusercontent.com/126913926/227732156-9e387922-4bf0-49b1-9c34-c64209bd824c.jpg)
For example, it happens with this link: http://bit.ly/3JKhtIF

**Comment by 1fexd** [comment]
Are you resolving urls locally or are you using the external service option?

**Comment by not-programmer98** [comment]
It worked after disabling follow redirects option, but I hope you fix it cause I don't like to disable.
No, I'm not using external service  Option.
Also another notice, privacy policy link in this option leads to a page with 404 error.

**Comment by 1fexd** [comment]
Strange, it works fine for me. Can you provide a logcat?

**Comment by not-programmer98** [comment]
I don't know how to do that but it works fine if I enabled  follow redirects via external service or if disabled the whole follow redirects

**Comment by 1fexd** [comment]
Closing this issue as it has been inactive for two months. Please open a new one if the issue persists.
