### ISSUE TITLE
[Feature Request] Top button to close Linksheet  

### ISSUE THREAD

**Issue by Terkyz** [1fexd/LinkSheet#49]
Maybe I press a link by mistake, or I just want to do something on my current app before heading to the next one, a button to close Linksheet would be great, of course this one in case Linksheet is on "Always ask" 

[Here](https://i.imgur.com/anV4tv0.jpg) an image with example purposes

**Comment by 1fexd** [comment]
Just go back using the back button. I don't think this request adds any value, sorry.
