### ISSUE TITLE
Custom Tabs not handled by the default browser, but Chrome instead 

### ISSUE THREAD

**Issue by JasonHK** [1fexd/LinkSheet#50]
In some apps, external links doesn't open in the Custom Tab of a default browser (for example, Firefox), but Chrome instead. This is also the case for Trusted Web Activity.

**Comment by 1fexd** [comment]
Can you provide an example?

**Comment by JasonHK** [comment]
> Can you provide an example?

For Custom Tabs:

- Twitter will open links with Chrome Custom Tab
- But Telegram will open links in Custom Tab with the browser of your choice

For Trusted Web Activity:

- All apps I've tested use Chrome to handle the interface
- This is one of those that don't work: <https://play.google.com/store/apps/details?id=com.penana.webapp>

All of the issues above don't occur when the default browser wasn't set to LinkSheet

**Comment by 1fexd** [comment]
I'm not quite sure I can follow, could you provide a screen recording where you showcase all of those cases?

**Comment by 1fexd** [comment]
Closing this as it has been inactive for two months. Open an new issue if the issue persists.
