### ISSUE TITLE
In app browser issue Reddit.

### ISSUE THREAD

**Issue by bart7782** [1fexd/LinkSheet#53]
When I click a YouTube link in Reddit, it opens in a in-app browser. Usually that would be chrome, and i would click in the top to open it in chrome instead of the in-app browser. Now with linksheet as my default browser, it opens a different in-app browser. I would expect it ask where to open the link, instead of opening some janky in-app browser

**Comment by 1fexd** [comment]
Apparently you can't disable the inapp browser anymore so there's nothing I can do about that

**Comment by 1fexd** [comment]
> What browser is it using to open this though? 
> Before it was using chrome but now that my default browser is LinkSheet it uses some janky worse browser that does not scale well.

Probably the system webview, could you provide a screenrecording?

> Is it possible to get LinkSheet recognized as an in-app browser and immediately redirect to the full app. Like Chrome does when you click the button to view site in Chrome.

I don't think so

**Comment by bart7782** [comment]
https://user-images.githubusercontent.com/64976181/230220340-5b29a672-e48e-4725-aab9-8b3d5321e1b6.mp4

**Comment by 1fexd** [comment]
Do you have the inapp browser enabled in Reddit?

**Comment by bart7782** [comment]
I don't see a setting for that anywhere in the Reddit app

**Comment by 1fexd** [comment]
Yes you are absolutely right. I have already stated above that they seem to have removed the option to use an external browser. I suggest using a third party client.

**Comment by Terkyz** [comment]
I have a similar problem but I don't know if it's related and I didn't want to open an issue for something that already happened, but on my phone I have two browsers (Vivaldi and Firefox), Vivaldi is specifically to use it for work purposes, and Firefox is my personal browser. When using an app like Nunti (which uses webengine) I open a news, this news is ALWAYS opened in Vivaldi even if I have in Linksheet Firefox as preferred browser, and if I set Firefox as the default browser then the news is opened in Firefox webengine, is this even correctable?

**Comment by 1fexd** [comment]
> When using an app like Nunti (which uses webengine) I open a news, this news is ALWAYS opened in Vivaldi even if I have in Linksheet Firefox as preferred browser,

The browser you set as preferred in LinkSheet has nothing todo with the Android system, it's just LInkSheet internal.

I don't know how Android determines which browser to use for webviews when the default browser is set to an app which can't handle webviews (like LinkSheet), but I will look into it.

**Comment by 1fexd** [comment]
I have to dig deeper into the Android/Chromium source code to find out why this happens and if I can "override" this behaviour (I fear it won't possible). In the meantime, consider using [AntiWebView](https://github.com/1fexd/AntiWebView)
