### ISSUE TITLE
ClearURLs setting causing gmail link to be broken

### ISSUE THREAD

**Issue by squeak9** [1fexd/LinkSheet#54]
I tried to click a link in gmail but I had the clearURLs setting enabled and it stripped the important parts of the url.

A similar link as an example: 

`https://www.google.com/url?q=https://minecrafthelp.zendesk.com/requests/9999999999999999999/satisfaction/new/asfdasfasfasfasdasdasdasdasd?locale%3D1%26intention%3D16&source=gmail&ust=999999999999999999999&usg=asdafsasfasfasfasfaf`

To reproduce:

1. Copy the url above on your phone.
2. Open LinkSheet 0.0.29.
3. Enable clearURLs setting.
4. It should show you the link in your clipboard, try to open it.

It should take you to a google page that redirects you to zendesk but instead you end up on google without the redirect.

**Comment by 1fexd** [comment]
Thanks for the report, will be fixed in the next build.
