### ISSUE TITLE
Unable to open some links

### ISSUE THREAD

**Issue by garvongithub** [1fexd/LinkSheet#56]
![Screenshot_2023-04-07-00-49-39-90_285d321a7f2b4caadf3755a2e711c9e5.jpg](https://user-images.githubusercontent.com/77321589/230474731-396ebadd-9f71-4d4b-99fc-11c339fbc4e7.jpg)

Links open successfully if I remove link sheet and set my browser as default.

https://www.google.com/search?q=Skip%20and%20Loafer%20TV%20Series

https://duckduckgo.com/?q=Skip%20and%20Loafer%20TV%20Series

https://m.youtube.com/results?search_query=Skip+and+Loafer+TV+Series

Screen recording- https://imgur.com/a/bInCmib

**Comment by 1fexd** [comment]
What link related settings do you have enabled? Can you provide a logcat?

**Comment by garvongithub** [comment]
![Screenshot_2023-04-08-17-25-36-29_338d1168706d12c5c38fa9d3a60e24f4.jpg](https://user-images.githubusercontent.com/77321589/230719883-5a35dedc-304f-47eb-9f7f-eddf4dea1fb4.jpg)

![Screenshot_2023-04-08-17-25-41-60_338d1168706d12c5c38fa9d3a60e24f4.jpg](https://user-images.githubusercontent.com/77321589/230719880-7e228641-42ab-42b8-bab1-3bcd114e2076.jpg)

![Screenshot_2023-04-08-17-25-27-84_338d1168706d12c5c38fa9d3a60e24f4.jpg](https://user-images.githubusercontent.com/77321589/230719881-beef5368-e16d-41a9-b1a0-36f1f28579de.jpg)

![Screenshot_2023-04-08-17-25-20-16_338d1168706d12c5c38fa9d3a60e24f4.jpg](https://user-images.githubusercontent.com/77321589/230719882-a9aa2b9d-6040-4abb-9f57-236fb5be4936.jpg)

These are all the settings I have changed, others are all default. In case you would like to see the app where this happens, I have linked the app below. It happens in the links section of shows and movies. I don't really know how to do the adb stuff, if the problem is still not confirmed then, I will look into it and provide the logcat.

https://github.com/michaldrabik/showly-2.0

**Comment by 1fexd** [comment]
Very strange, it does not crash for me. I have described the process of creating a logcat in [this issue](https://github.com/1fexd/LinkSheet/issues/47)

**Comment by 1fexd** [comment]
Closing as this has been inactive for two months. Please open a new one if the issue persists.
