### ISSUE TITLE
[Feature suggestion] Save Media From Link

### ISSUE THREAD

**Issue by GL513** [1fexd/LinkSheet#57]
When opening links, try to resolve them, and if the link is raw media (video, image, audio, text file...) allow user to download media to custom path, or if the user doesn't want the item downloaded, copy the media to the clipboard so it can easily be discarded.
This is particularly handy for downloading media from a link that has been opened from one userspace (using Oasis Feng's "Island" work profile provisioner and manager) into another userspace.

**Comment by 1fexd** [comment]
Have you considered using LinkSheet to launch another app for this purpose? FV File manager seems to offer this option. I'm not sure this is in the scope of LinkSheet, I'd rather keep it simple and delegate such functionality to another app.

**Comment by GL513** [comment]
I understand what you mean, but I did some digging, and there doesn't seem to be much but FV File Manager. I don't think there needs to be a whole file manager just for a quick web get.
Maybe if this can't be directly implemented into linksheet that it could be an extension in the future, one that doesn't require hopping around using the "share to" button, although I understand making an extension functionality can be an undertaking.
Besides, I prefer to use FOSS when I can anyway.

**Comment by GL513** [comment]
@1fexd would it be possible to add a notification or toast saying that the item has been downloaded?
I used the feature earlier and clicked it multiple times only to realize I had 15 dupes haha
Maybe if a notification is added, it can be used to open the file on click.

**Comment by 1fexd** [comment]
You are absolutely right, thanks. Will be fixed in the next build.
