### ISSUE TITLE
[Feature Suggestion] Resolve Google Amp links as regular links

### ISSUE THREAD

**Issue by GL513** [1fexd/LinkSheet#58]
Have a toggle to redirect the amp URLs to the normal webpages

**Comment by TontyTon** [comment]
This would be very helpful.
Amputator Bot might be helpful to ease implement this feature.

**Comment by 1fexd** [comment]
Is this really required? Every AMP link I have encountered while testing automatically redirects me to the full page.

**Comment by GL513** [comment]
It doesn't seem to work for me with Firefox nor Chrome

**Comment by 1fexd** [comment]
Would you mind sharing the links?

**Comment by soymadip** [comment]
does an app even share AMP links?

**Comment by TontyTon** [comment]
@soymadip Other people send amp links, also some apps give amp links in References/More Reading sections.

@1fexd One amp link is https://historia.nationalgeographic.com.es/a/civilizacion-valle-indo-es-mas-antigua-que-egipcia-y-babilonica_6828/amp

I just searched for replies by amputator bot on reddit.
If you want more links, please ask me or check the messages to which AmputatorBot has replied to https://www.reddit.com/search/?q=amputator%20bot&type=comment

BTW, we want to convert amp links to normal links for several reasons, personally for me reasons are privacy and moral reasons. Detailed reasons can also be read at https://www.reddit.com/r/AmputatorBot/comments/ehrq3z/why_did_i_build_amputatorbot/ , 1st point.

**Comment by soymadip** [comment]
> @soymadip Other people send amp links, also some apps give amp links in References/More Reading sections.
> 
> @1fexd One amp link is https://historia.nationalgeographic.com.es/a/civilizacion-valle-indo-es-mas-antigua-que-egipcia-y-babilonica_6828/amp
> 
> I just searched for replies by amputator bot on reddit.
> If you want more links, please ask me or check the messages to which AmputatorBot has replied to https://www.reddit.com/search/?q=amputator%20bot&type=comment
> 
> BTW, we want to convert amp links to normal links for several reasons, personally for me reasons are privacy and moral reasons. Detailed reasons can also be read at https://www.reddit.com/r/AmputatorBot/comments/ehrq3z/why_did_i_build_amputatorbot/ , 1st point.

Hmm looks like there are then.

**Comment by TontyTon** [comment]
Hey, I tried the latest nightly. It seems like it uses internet to unAMP (most of) the links.
Is it not possible to unAMP offline? As using online service involves a compromise to privacy.

**Comment by 1fexd** [comment]
Doesn't seem to be possible, but why do you think it compromises your privacy? The website will get your IP nonetheless, and it probably also uses Google fonts or Analytics so Google will also track you, regardless of wheter you are using the AMP version of the page or not.

**Comment by TontyTon** [comment]
Ohk, if it's not possible then okay, better than nothing, I would just suggest you to inform the user in the option's description that online connection will be made (for all or only amp links) and who will be contacted for that.
About privacy, I assumed you are using 3rd party service to unAMP the link. Am I wrong?
About google getting to know, if the link was unAMPed offline, then google won't know, I (and many others) block all of google, especially analytics.
Otherwise too it may be a issue, like sometimes one may choose to open some link in a browser with proxy, then user's IP can be leaked, that's why I suggested to inform the user (in first line of this comment).

**Comment by 1fexd** [comment]
> Ohk, if it's not possible then okay, better than nothing, I would just suggest you to inform the user in the option's description that online connection will be made (for all or only amp links) and who will be contacted for that.

Yep, will implement that.

> About privacy, I assumed you are using 3rd party service to unAMP the link. Am I wrong?

By default the app resolved the AMP link locally, but the user can choose to use an API I have written and deployed to [supabase](supbase.com) (more info [here](https://github.com/1fexd/LinkSheet/blob/master/PRIVACY.md))

**Comment by TontyTon** [comment]
Ohkay. Thanks a lot.
