### ISSUE TITLE
[Bugs] set LinkSheet as default browser

### ISSUE THREAD

**Issue by Nonanne** [1fexd/LinkSheet#59]
**Android version**: 10
**Device**: Xiaomi MI9 (miui 12.5 / disable miui customization)
**App version**: 0.0.29

I have set LinkSheet as default browser. I can't change in-app browser (I want to use Firefox but it use Chrome) is that has any option that I missing?

**i.e** Set LinkSheet as default browser in phone settings
then open [youtube.com](youtube.com) in Twitter app (in-app browser settings enable)
It force me to open in-app browser preview with Chrome _(screenshot no.1)_
> before this I always use Firefox for in-app browser
It doesn't display pop-up _(screenshot no.2)_ that should display when I already set browser default

screenshot this when press url
![blur51681412223478.jpg](https://user-images.githubusercontent.com/94383254/231857054-dc1d2164-668b-4848-865f-eec7840d755b.jpg)

this should display instend first one above
![blur11681412247379.jpg](https://user-images.githubusercontent.com/94383254/231857352-bcc5250e-9e04-4ee5-a368-1324d5abacca.jpg)

**Comment by 1fexd** [comment]
I'm not sure at all but maybe this has something todo with the fact that LinkSheet does not provide a WebView? Have you considered toggling off the Twitter in-app browser? That should open LinkSheet directly when you press a link (works for me)

**Comment by 1fexd** [comment]
I'm not sure, will look into that.

**Comment by 1fexd** [comment]
Fixed in c796b2e
