### ISSUE TITLE
show support apps when bypass redirect

### ISSUE THREAD

**Issue by Nonanne** [1fexd/LinkSheet#61]
in this record I open url in youtube app that have redirect url. Can it show support app (twitter in this case) in first time? (for now, it doesn't show in first time. I need to use open with and open LinkSheet again to show twitter icon)

https://user-images.githubusercontent.com/94383254/231885807-435a1800-0987-4042-9bcc-699fd3e29800.mp4

**Comment by 1fexd** [comment]
Do you have the ClearURLs integration enabled?
