### ISSUE TITLE
Fastlane: changelog oversized

### ISSUE THREAD

**Issue by IzzySoft** [1fexd/LinkSheet#63]
Fastlane's per-release changelogs are limited to 500 char each. Your current one (`29.txt`) has 1128 chars and thus will be truncated. It also should only contain the changes for the current release, not the entire history. Can you please (at least for future releases) stay within the 500 char limit? Thanks in advance!

**Comment by 1fexd** [comment]
Oh, I didn't know that - will do.

**Comment by IzzySoft** [comment]
Thanks! I've shortened `29.txt` accordingly on my end meanwhile (to get rid of the warning).
