### ISSUE TITLE
Add support for default app being a browser 

### ISSUE THREAD

**Issue by paerbac** [1fexd/LinkSheet#64]
I would like to be able to open YouTube links in a separate browser from my main one. As of right now, browsers are not supported with specific app opening to my understanding.

**Comment by 1fexd** [comment]
I don't quite understand what you mean by that.

**Comment by paerbac** [comment]
I would like to set the preferred app for specific links to be a secondary browser rather than my default browser. 

Like let's say I wanted my default browser to be brave, but wanted to open up YouTube links or Twitter links in the Firefox or kiwi browser while still having my default browser be brave.

**Comment by 1fexd** [comment]
I don't know man, that sounds like a lot of work for little outcome, is it really that annoying to not set a default browser and choose the one you want to use when LinkSheet opens?

**Comment by 1fexd** [comment]
I have added this to my todo list with low priority. I **may** implement this in a future release, but I can't/won't provide an ETA.
