### ISSUE TITLE
App getting loop crashes when i try to open amazon links through gmail

### ISSUE THREAD

**Issue by soumyadip69** [1fexd/LinkSheet#67]

**Comment by 1fexd** [comment]
Gonna need more info on that one chief. 

* Can you provide such a link? (please redact url queries etc.)
* Can you provide a logcat?
* What link manipulation settings do you have enabled?

**Comment by soumyadip69** [comment]
Sry it's my bad ,maybe i had set preferred browser as chrome  but my linksheet browser status app set as linksheet. I have installed again & didn't messed up with settings now its  fine 🔥 thanks sir for the app u saved our precious time 🙏🙏
