### ISSUE TITLE
Links aren't getting opened in prefered app.

### ISSUE THREAD

**Issue by soymadip** [1fexd/LinkSheet#69]
If we select an app for a link as 'always', the link isn't opening in prefered app. (If preferred browser is set as always ask)

Instead app shows all eligible apps again.

Screen record:- 

https://user-images.githubusercontent.com/84225810/234620647-958c87ae-9a9e-4e33-845c-9b3b366905b1.mp4

**Comment by 1fexd** [comment]
Your screenrecording appears to be broken.

**Comment by soymadip** [comment]
> Your screenrecording appears to be broken.

Oh, sorry for inconvenience

Here's new one:- 

https://user-images.githubusercontent.com/84225810/235302285-b91f52da-069c-4159-8a73-afac71843e36.mp4

- If the video is not loading again then here's the steps to reproduce the bug:- 

1.click on any link to open it
2.when linksheet opens, long press the app/browser you want to open the link in and select always. 
3. Now click on the link again, the sheet will ask you to choose app/browser again instead of directly opening it in previously selected app.

**Comment by 1fexd** [comment]
Your video is still broken. I can't reproduce the bug by following your steps.

**Comment by soymadip** [comment]
> Your video is still broken. I can't reproduce the bug by following your steps.

What? Did you tried the steps below the video?

So in your device if you select an app as 'always' for a link, it opens it automatically?

**Comment by soymadip** [comment]
And one thing, select the preferred browser as  'always ask' in the settings

**Comment by soymadip** [comment]
> Your video is still broken. I can't reproduce the bug by following your steps. 

And one thing i wanna ask, 
The 'alws' button is to best a link to open in an app automatically right? 
This one:-
![IMG_20230430_011652.jpg](https://user-images.githubusercontent.com/84225810/235321483-0661c114-561c-416c-b2f3-2bb9c8c8d6a4.jpg)

**Comment by 1fexd** [comment]
I have tried your steps, but I wasn't able to reproduce the bug. It works fine for me. Can you try to re-upload the video?

**Comment by soymadip** [comment]
> I have tried your steps, but I wasn't able to reproduce the bug. It works fine for me. Can you try to re-upload the video?

oh, sorry i should have been more clear😥.

- Here is a more detailed information & steps:-

Android 12 has 'open links in app' option to by default open a app's supported deep link in the app when the link is pressed. 

as example lets say for Github's mobile app, **it supports https://github.com links**.
**now if we turn off the 'open links in app' from settings** and click a link 'https://github.com', linksheet opens and shows the github app along with the browsers and if any other installed app which supports 'https://github.com'.

now if from popup, we select a app/browser to always open 'https://github.com' to that app by clicking **always**, thats where the bug is.
next time when we click 'https://github.com', **linksheet again pops up the Url-App-Chooser page** instead of **automatically opening the link in previously selected app**.



- steps to reprodece:- 

Lets say i have 1 browser and github mobile app's installed in my phone & i wanna open https://github.com/ links to the browser.
so first turn off 'open links in app' option from github mobile's settings 
![WhatsApp Image 2023-05-04 at 9 46 30 AM](https://user-images.githubusercontent.com/84225810/236114690-9f90b70c-61d7-4e97-b248-fa814042c106.jpeg)

now tap on 'https://github.com/' link from anywhere and linksheet opens Url-App-Chooser popup showing the browser and github mobile app.
![WhatsApp Image 2023-05-04 at 10 05 17 AM](https://user-images.githubusercontent.com/84225810/236113766-4259a589-6139-44e4-a954-41c16cd502b7.jpeg)

now long press the browser(in my case iceraven) and select the option 'alwa' from bottom-right corner. the link opens in browser.

now close browser and again click om 'https://github.com' and linksheet shoud open the link automatically in browser right? 
but linksheet again shows the Url-App-Chooser popup.








i guess now the bug should be understandable

**Comment by soymadip** [comment]
new recording (it should work in PC):-

https://user-images.githubusercontent.com/84225810/236116788-c7dfa95c-7dbb-4c89-a88d-c95bd2c372de.mp4

**Comment by Joyogirl** [comment]
Yeah, this problem is happening to me too. 
I am on Android 13.

**Comment by Joyogirl** [comment]
@1fexd please fix this

**Comment by soymadip** [comment]
@1fexd sorry to pimg but i see you changed the label, so did you understand what i was sayiing?😅

**Comment by 1fexd** [comment]
Yes

**Comment by soymadip** [comment]
> Yes

🙃finally.

**Comment by 1fexd** [comment]
Just tested on the latest dev version, looks like this is not an issue anymore. Going to release a new version later.

**Comment by soymadip** [comment]
> Just tested on the latest dev version, looks like this is not an issue anymore. Going to release a new version later.

Thanks a lost sir,  please release the fix version asap🙏

**Comment by soymadip** [comment]
@1fexd the 'always' button is still not working, if we turn off 'open links in app' and use the linksheet popup to select a app/browser to always, it still again is displaying the app chooser sheet

**Comment by 1fexd** [comment]
Very strange, still can't reproduce this. Gonna send you a debug build later.

**Comment by soymadip** [comment]
> Very strange, still can't reproduce this. Gonna send you a debug build later.

If you don't mind can you do a screen record and send me, i just wanna see i can explain correct problem

**Comment by 1fexd** [comment]
I have uploaded a debug build [here](https://transfer.sh/jUWYEQ/LinkSheet-0.0.31-debug.apk). Can you connect your phone to a PC, setup up the debug app, start a logcat like described [here](https://github.com/1fexd/LinkSheet/issues/47#issuecomment-1484043185) and try opening the link again. Then paste the contents of the logcat to this issue.

**Comment by soymadip** [comment]
> I have uploaded a debug build [here](https://transfer.sh/jUWYEQ/LinkSheet-0.0.31-debug.apk). 

The link is broken i guess (also tried using VPN, but showing file not found)
![Screenshot_2023-05-06-01-34-43-79_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/84225810/236558833-4cb45602-0dbd-4de6-bb58-588175ebc3a3.jpg)

**Comment by 1fexd** [comment]
I have reuploaded it [here](https://send.ephemeral.land/download/60623a7b576cc584/#4990hlE-_szXemaTojF53Q)

**Comment by soymadip** [comment]
> I have reuploaded it [here](https://send.ephemeral.land/download/60623a7b576cc584/#4990hlE-_szXemaTojF53Q)

Ok, i will send by tomorrow (because somehow adb doesn't work in my pc so i gotta wait for my dad's laptop)

**Comment by 1fexd** [comment]
No pressure. Also if you want you can describe why it's not working on your PC and maybe I can tell you what's wrong.

**Comment by soymadip** [comment]
> No pressure. Also if you want you can describe why it's not working on your PC and maybe I can tell you what's wrong.

Please tell me🥲

**Comment by soymadip** [comment]
> No pressure. Also if you want you can describe why it's not working on your PC and maybe I can tell you what's wrong.

how to generate log file? its showing logs in terminal though

i copied the log and manually created a log.txt
[LogCat.txt](https://github.com/1fexd/LinkSheet/files/11422590/LogCat.txt)

**Comment by 1fexd** [comment]
You need to click a link, not open the settings.

**Comment by soymadip** [comment]
> You need to click a link, not open the settings.
Actually, i mistakenly went to settings..

I did go through the link opening after that....

**Comment by soymadip** [comment]
I will record again tonight then

**Comment by soymadip** [comment]
> You need to click a link, not open the settings.

there you go:-
[LogCat.txt](https://github.com/1fexd/LinkSheet/files/11442199/LogCat.txt)

hope this one's good

**Comment by 1fexd** [comment]
I have attempted to fix the bug. You can download the new debug release [here](https://send.ephemeral.land/download/8716d1557105d152/#ES1J28Q-zZNzUbnLqUAgsg). Please check if it works, and if not, please provide another logcat. Thanks.

**Comment by soymadip** [comment]
> I have attempted to fix the bug. You can download the new debug release [here](https://send.ephemeral.land/download/8716d1557105d152/#ES1J28Q-zZNzUbnLqUAgsg). Please check if it works, and if not, please provide another logcat. Thanks.

I don't know if i was able to explain the problem correctly 😅

Please sir if you don't mind can you send me a screen record of you doing the process? 

I just wanna know if it's my phone's problem

**Comment by soymadip** [comment]
> I have attempted to fix the bug. You can download the new debug release [here](https://send.ephemeral.land/download/8716d1557105d152/#ES1J28Q-zZNzUbnLqUAgsg). Please check if it works, and if not, please provide another logcat. Thanks.

Just installed one of your old releases [V 0.0.21]

**Comment by soymadip** [comment]
> In `0.0.28-debug` the toggle `Never show "last picked app" section` was introduced in the `Bottom sheet ` settings section - this seems to break the `Always` button - you probably have that feature enabled, right?

Ohhh I guess that's right. 

I didn't find the 'never show the last picked section' in earlier builds

**Comment by soymadip** [comment]
I hope that's fixed. 
Closing this one then.

**Comment by Dhyfer1** [comment]
@soymadip Has your problem already been solved? I have the same problem when using linksheet with Revanced. 

If you have already solved your problem, what did you do to do it? What version of linksheet are you using now?

**Comment by soymadip** [comment]
> @soymadip Has your problem already been solved? I have the same problem when using linksheet with Revanced. 
> 
> If you have already solved your problem, what did you do to do it? What version of linksheet are you using now?

Well @1fexd fixed it, but hasn't released it. 

But for now as a workover,  disable the 'never show the last picked section'..

**Comment by Dhyfer1** [comment]
> Well @1fexd fixed it, but hasn't released it.
> 
> But for now as a workover, disable the 'never show the last picked section'..

Thank you so much. I have disabled that option and a link to YouTube now opens directly in Revanced, (before it opened in the browser)

But it works when I click a Youtube video link in Google search results, but not when I click a Youtube video link from Google Discover 🙄

@1fexd Can you fix it?

**Comment by 1fexd** [comment]
> But it works when I click a Youtube video link in Google search results, but not when I click a Youtube video link from Google Discover roll_eyes

What's Google Discover? What happens when you click a Youtube link there? Can you grab the latest nightly build from [here](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip) (can be installed side by side with the release build) and test if the issue is still present?

**Comment by soymadip** [comment]
> > But it works when I click a Youtube video link in Google search results, but not when I click a Youtube video link from Google Discover roll_eyes
> 
> * What's Google Discover? 
> * What happens when you click a Youtube link there? 
> * Can you grab the latest nightly build from [here](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip) (can be installed side by side with the release build) and test if the issue is still present?

Google discover is the news page when you swipe right in pixel devices....

**Comment by soymadip** [comment]
And @Dhyfer1 it's designed to open links  in Google app or Chrome custom tabs...

**Comment by Dhyfer1** [comment]
> * What's Google Discover?
> * What happens when you click a Youtube link there?
> * Can you grab the latest nightly build from [here](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip) (can be installed side by side with the release build) and test if the issue is still present?

* Google Discover is a section within the new tab page in Chrome, where you can see any content: news, videos, articles etc, as shown in the video
* When I click on a link supported by Youtube, the link just opens a new Chrome tab, as shown in the video, instead of opening in Revanced.
* The problem in my case is still present, I used the last build you told me but there is no result. Maybe I'm using wrong linksheet? You need to explain in the readme how to use your app.

I couldn't upload the video to my message because of its size, so you can see the video I'm talking about [here](https://drive.google.com/file/d/16oTglVZGYGqZZVWjipMdlGoDQzjgi455/view?usp=sharing) And [here](https://drive.google.com/file/d/18mAWRkQY4gUC1ZXmguve22I3qS1U8dvw/view?usp=sharing) is another video where if I click on a link to a youtube video in the search results, then the video does open in Revanced 

As you can see, my problem is similar to @soymadip. Is there anything that can be done about it?

**Comment by 1fexd** [comment]
What happens if you install the normal Youtube app? Do Youtube links clicked in "Discover" automatically open in the normal Youtube app? If not, this is a issue with Chrome, not LinkSheet (looks like Chrome does not send a intent (which, in simple terms, is just a request to the Android system to open something in another app) when the link is clicked in Discover). 

> You need to explain in the readme how to use your app.

I plan to include an app-intro and a detailed setup guide in the next release.

**Comment by Dhyfer1** [comment]
> What happens if you install the normal Youtube app? Do Youtube links clicked in "Discover" automatically open in the normal Youtube app? If not, this is a issue with Chrome, not LinkSheet 

Hmm. The same thing happens with the YouTube app. If I click on a Youtube link from Discover, it just opens the video in a new tab, it's weird because within the settings for the YouTube app, the m.youtube.com link should automatically open on Youtube app, as it happens in the second video where if it does the job. 

So it's a problem that only happens with YouTube links in Discover, but not with YouTube links in search results. Is it possible to force linksheet to open YouTube links from Discover in the YouTube or Revanced app?

> I plan to include an app-intro and a detailed setup guide in the next release.

Great. I look forward to the new version soon.

**Comment by 1fexd** [comment]
> So it's a problem that only happens with YouTube links in Discover, but not with YouTube links in search results. Is it possible to force linksheet to open YouTube links from Discover in the YouTube or Revanced app?

As already mentioned, LinkSheet is only started when an app explicitly sends an Intent to the system requesting that the content be opened in another app. Looks like Chrome doesn't do that when a link is clicked in Discover, so sadly, there's nothing I can do about that.

> Great. I look forward to the new version 

Btw, you are very welcome to test the nightly builds (new build on each commit) and report bugs ;)

**Comment by Dhyfer1** [comment]
> As already mentioned, LinkSheet is only started when an app explicitly sends an Intent to the system requesting that the content be opened in another app. Looks like Chrome doesn't do that when a link is clicked in Discover, so sadly, there's nothing I can do about that.

It's okay, I understand. No problem 

> Btw, you are very welcome to test the nightly builds (new build on each commit) and report bugs ;)

Yes, thanks for the help. By the way, I hope the next stable version will have the app-intro and detailed setup you're talking about. ;)
