### ISSUE TITLE
Clicking links from youtube video descriptions 

### ISSUE THREAD

**Issue by dgudim** [1fexd/LinkSheet#7]
Clicking links from youtube video descriptions does not bring up LinkSheet.
Here are the only matching activities
![Screenshot_20230225_085623_App Manager](https://user-images.githubusercontent.com/34401005/221343539-57ccff35-9acc-48da-ba54-1b10adb795e0.jpg)

**Comment by 1fexd** [comment]
Thanks for reporting this bug.
