### ISSUE TITLE
[Feature Request] Add option to set custom browser when an app oens a in-app browser tab

### ISSUE THREAD

**Issue by Joyogirl** [1fexd/LinkSheet#71]
when an app opens a in-app browser tab, linksheet opens the link in preferred browser if we have selected a browser as preferred from linksheet settings. 

but if we **haven't set** a preferred browser (like it's set to always ask..) ; linksheet **opens a popup to select browser** and then opens the tab in browser. 

https://user-images.githubusercontent.com/93784753/236188355-474b8d94-23d2-4130-b4b9-01c5b13d5324.mp4

so if an option is added to set a **'preferred in-app browser'** separately from **'preferred browser'**, it will be really helpful.

**Comment by Joyogirl** [comment]
Please fix the #69 first please though, it's a crucial (and annoying) bug

**Comment by soymadip** [comment]
Thanks DEV
