### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by 1fexd** [1fexd/LinkSheet#8]
Hey there @IzzySoft, I have updated the screenshots in the readme, can you update them in your repo too?

**Comment by IzzySoft** [comment]
Automatically with each new release if we've set up fastlane accordingly (i.e. you have fastlane established and I have all features enabled). If you need a "refresh" between releases, that would be a manual job and hence it would help to mention the package name (you know yours by heart – with 1k+ apps in my repo I'll have to guess :wink:)

    fe.linksheet: no Fastlane configured, skipping Fastlane check.

Hm, so we have not it seems – hence no automatic updates. Would you be willing to establish Fastlane? I could send you a "starter package" via PR, and you then could adjust to your liking. There's always my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance.

**Comment by 1fexd** [comment]
> Hm, so we have not it seems – hence no automatic updates. Would you be willing to establish Fastlane? I could send you a "starter package" via PR, and you then could adjust to your liking. There's always my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance.

That sounds fantastic!

**Comment by IzzySoft** [comment]
On its way! :smiley:

**Comment by 1fexd** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Gladly! And thanks for adding the per-release changelogs! I've just enabled that here now and triggered a manual pull, so it should show up with the next sync tomorrow then.
