### ISSUE TITLE
Add LinkSheet to Weblate to promote localization

### ISSUE THREAD

**Issue by StoyanDimitrov** [1fexd/LinkSheet#81]
Weblate sponsors open source projects and it's super easy to integrate. On top of that Weblate is open source itself.

Here is a link to the [application form](https://hosted.weblate.org/hosting/) (you have to register first). After short approval LinkSheet will be available to translators. In Weblate [projects list](https://hosted.weblate.org/projects/) you may find many great open source apps.

**Comment by 1fexd** [comment]
Already started to set it up the other week, but got frustrated with the very unintuitive setup, but I'll try again

**Comment by StoyanDimitrov** [comment]
Well, to be fair I've heard that from other developers too. What are your main pain points?

**Comment by Daviteusz** [comment]
This is how my config looks for pull requests:
![obraz](https://github.com/1fexd/LinkSheet/assets/11527277/cc97d801-c918-49f4-9873-f09f79f6d70c)

This is how the automatic push to the repository should look like:
(I don't remember correctly)
![obraz](https://github.com/1fexd/LinkSheet/assets/11527277/e46a2308-0f07-4cc0-81db-d89fd9801c03)

Maybe helpful link:
https://docs.weblate.org/en/weblate-4.17/vcs.html#vcs-repos

**Comment by 1fexd** [comment]
My request for libre hosting has been approved. Weblate is now available [on the official instance](https://hosted.weblate.org/projects/linksheet/)

**Comment by Daviteusz** [comment]
@1fexd 41 strings are missing in Weblate 😢
![obraz](https://github.com/1fexd/LinkSheet/assets/11527277/05119eb7-2f9e-4c3c-a187-c13cd85f96f4)

**Comment by 1fexd** [comment]
Should be fixed now
