### ISSUE TITLE
Build debug/release apk using actions

### ISSUE THREAD

**Issue by Daviteusz** [1fexd/LinkSheet#88]
Hello, I have created a workflow file to build LinkSheet using github actions.
I wanted to use this, to test the translation, but the application throws an error when launched:
<img src=https://github.com/1fexd/LinkSheet/assets/11527277/19376b26-e9a5-45f2-8ff0-3a004b501957 width=10%>
I don't know how to solve this, but it may be useful.
https://github.com/Daviteusz/LinkSheet/blob/master/.github/workflows/build-debug.yml

**Comment by 1fexd** [comment]
Ah yes, I haven't done a release build yet (releases are minified) and therefore didn't catch this error - should be fixed now. Btw, I stole your workflow ;)
