### ISSUE TITLE
[Suggestion] Horizontal grid selection view

### ISSUE THREAD

**Issue by Gravemind2015** [1fexd/LinkSheet#9]
Hey, thanks a ton for this app, this new default app behaviour was annoying as many apps like infinity (reddit) and newpipe (youtube) weren't being shown when not selected as default.

Since the app is relatively new, I was wondering if we could also have a grid layout for apps. Attached picture is one implementation I've experienced, and the advantages are bigger target areas and icons being used as the main identification instead of (package) name.

Obviously this would be a very low priority UI option rather than a regression/bug, but it'd be nice to have opinions about a grid layout in addition to list.

I'll also have a suggestion about app list sorting behaviour, which could be mitigated somewhat with a grid layout. I'll try to post that in a separate issue and linking here.

![Screenshot_20230226-221002_Android System_1](https://user-images.githubusercontent.com/116586720/221424337-edc6062a-5720-41d7-ae27-abdbcf9560df.png)

**Comment by xmha97** [comment]
Why did you install all versions of Firefox?

**Comment by Gravemind2015** [comment]
> Why did you install all versions of Firefox?

1. Firefox focus is set as assistant so that's available with swipe up from bottom. For quick searches.
2. Bromite is the main browser with hundreds of tabs, all non-logged-in activities go here.
3. Fennec handles all logged-in stuff
4. Firefox and firefox beta are just there to keep track of changes as I'm waiting for them to add proper support for things like print to pdf (it was introduced but is barebones compared to chromium) and extensions.

**Comment by Gravemind2015** [comment]
Sorry, accidentally hit closed instead of send, my bad, I apologise.

**Comment by 1fexd** [comment]
Will implement in next release.

**Comment by xmha97** [comment]
> > Why did you install all versions of Firefox?
> 
> 1. Firefox focus is set as assistant so that's available with swipe up from bottom. For quick searches.
> 2. Bromite is the main browser with hundreds of tabs, all non-logged-in activities go here.
> 3. Fennec handles all logged-in stuff
> 4. Firefox and firefox beta are just there to keep track of changes as I'm waiting for them to add proper support for things like print to pdf (it was introduced but is barebones compared to chromium) and extensions.

Thanks for your reply.
Also install the Firefox nightly to use all Firefox add-ons on your phone.
