### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [1fexd/LinkSheet#94]
### Feature description

https://hosted.weblate.org/projects/linksheet/linksheet/#information says "GPLv3-only",
and it is usually the case that when the source repo doesn't specify one way or the other,
people mean to select "GPLv3-or-later".
That way it can be AGPLv3-or-later, or work for such programs, or potentially be GPLv4 in the future
without having to negotiate with many translators.

It can be changed in
https://hosted.weblate.org/settings/linksheet/linksheet/

:)

**Comment by 1fexd** [comment]
Updated
